### ISSUE TITLE
isPushNotificationsEnabled incorrectly reports false after 2nd visit

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Website-SDK#120]
`isPushNotificationsEnabled` correctly returns `false` before users accepts notifications and then `true` after they accept the native prompt. However after reloading the page it will continue to report false.

Issue reproduced on a https site without prompt off. Prompted from the bell icon.

**Comment by jasonpang** [comment]
Not currently able to reproduce; however we've gotten at least two reports of this and one of the other people might be willing to demonstrate this so leaving open until then.

**Comment by jasonpang** [comment]
Couldn't quite get hold of the person who was going to demonstrate the issue. Will open a second issue if this recurs.

**Comment by airs0urce** [comment]
As I see it happens when you call "isPushNotificationsEnabled" right during page loading. But if page loaded and you wait a little it start returning correct value.

And also for me it happens only one time, after user just logged in. After that he can reload page many times and isPushNotificationsEnabled will always return "true". May be it's related to the fact that I clear cookies or localStorage on each logout. Can't tell exactly. But after login I have to wait some time until OneSignal fetch correct value and and only then I can call "isPushNotificationsEnabled".

**Comment by sido420** [comment]
![screen shot 2017-12-17 at 11 36 54 pm](https://user-images.githubusercontent.com/32019406/34090219-5fe0cff4-e383-11e7-9624-27b8ba297947.png)

here is an example on a site where Chrome shows Notifications are allowed but OneSignal client does not detect it most of the times. This is well after the site has loaded.

**Comment by promatik** [comment]
Hi! It's happening exactly the same with me.
After a successfully subscription, after I refresh the page, isPushNotificationsEnabled returns false.
@sido420 did you solve the problem?

Here is my log:
```javascript
EVENTS.SDK_INITIALIZED_PUBLIC
isPushNotificationsEnabled: false

// Click to subscribe

EVENTS.REGISTERED
subscriptionChange: true

OneSignal.isPushNotificationsEnabled().then(e => console.log(e))
true

// Page refresh

EVENTS.SDK_INITIALIZED_PUBLIC
isPushNotificationsEnabled: false

```

**Comment by khaninD** [comment]
I am also experiencing this issue. isPushNotificationsEnabled return false after refresh page

**Comment by 4rthem** [comment]
Maybe not related to @jkasten2's case...
I had the same issue until I realized the `Update on reload` service worker option was checked.

![image](https://user-images.githubusercontent.com/2180032/68480496-43aaa300-0235-11ea-945c-acfd26ded340.png)

**Comment by kostiantyn-solianyk** [comment]
same issue even on newest sdk version, any updates?

**Comment by FrnandMG** [comment]
I still have this problem, any solution?

**Comment by jkasten2** [comment]
@FrnandMG We have changed the SDK quite a bit since this issue as reported. Can you provide exact steps and browsers with their version numbers where you see the issue?

**Comment by FrnandMG** [comment]
> @FrnandMG We have changed the SDK quite a bit since this issue as reported. Can you provide exact steps and browsers with their version numbers where you see the issue?

Thanks for answering... I am trying to deploy to a web with angular. "package onesignal-ngx". 
When the user subscribes, I try 
`"OneSignal.isPushNotificationsEnabled().then(e => console.log(e))" ---> "false"`
 in the chrome console. 
The rest is correct: 
```
OneSignal.getSubscription(), 
OneSignal.getUserId(),
OneSignal.getRegistrationId(),
OneSignal.getNotificationPermission(),
```
**But I don't get the notifications.**

I tried it on the following devices:
- win 10 chrome Version 101.0.4951.54 (Official build) (64 bits)
- win 10 brave Version 1.38.117 Chromium: 101.0.4951.67 (Official Build) (64-bit)
-android 10 chrome
-android 8 chrome

I tried the same appid in a simple html web and it works fine. the problem is with the angular package.

**Comment by jkasten2** [comment]
> I tried the same appid in a simple html web and it works fine. the problem is with the angular package.

Just to confirm, if you use the following code it works fine?
```html
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
<script>window.OneSignal = window.OneSignal || [];</script>
```
From this setup guide: https://documentation.onesignal.com/docs/web-push-sdk#initialization


If your issue is only with `onesignal-ngx` please open a new issue there with these details:
https://github.com/OneSignal/onesignal-ngx/issues

**Comment by sshanzel** [comment]
Still happens to me using `react-onesignal` - always returning false. Feels like this is an on-going bug.

**Comment by quyenvsp** [comment]
for people who have this problem and your website do have service worker, then check it maybe conflict service worker scope root '/'.

You must use [Custom code setup](https://documentation.onesignal.com/docs/onesignal-service-worker-faq#custom-code-setup---service-worker-customizations) and put it in subdirectory.

> change the OneSignal scope to anything you choose to make room for another Service Worker to be placed at the root scope. [document](https://documentation.onesignal.com/docs/onesignal-service-worker-faq#setup-type-1-default-onesignal-setup---scope-root---and-default-onesignalsdkworkerjs-contents)

if you still place it root '/' then will conflict and `isPushNotificationsEnabled` will be set to false at second time open app because
> /* You can't be subscribed without a service worker registration */

[SubscriptionManager.ts](https://github.com/OneSignal/OneSignal-Website-SDK/blob/main/src/managers/SubscriptionManager.ts#L748)

**Comment by Ismael-Hery** [comment]
> for people who have this problem and your website do have service worker, then check it maybe conflict service worker scope root '/'.
> 
> You must use [Custom code setup](https://documentation.onesignal.com/docs/onesignal-service-worker-faq#custom-code-setup---service-worker-customizations) and put it in subdirectory.
> 
> > change the OneSignal scope to anything you choose to make room for another Service Worker to be placed at the root scope. [document](https://documentation.onesignal.com/docs/onesignal-service-worker-faq#setup-type-1-default-onesignal-setup---scope-root---and-default-onesignalsdkworkerjs-contents)
> 
> if you still place it root '/' then will conflict and `isPushNotificationsEnabled` will be set to false at second time open app because
> 
> > /* You can't be subscribed without a service worker registration */
> 
> [SubscriptionManager.ts](https://github.com/OneSignal/OneSignal-Website-SDK/blob/main/src/managers/SubscriptionManager.ts#L748)

@quyenvsp you saved after hours of searching a solution!
