### ISSUE TITLE
OneSignal.registerForPushNotifications() doesn't call setSubscription(true) if the user is manually unsubscribed

### ISSUE THREAD

**Issue by pcarion** [OneSignal/OneSignal-Website-SDK#125]
Hi,

I am trying to implement a registration from our UI.

We have a button to subscribe, and when we click on it we call:

```
OneSignal.push(function() {
    OneSignal.registerForPushNotifications({
        modalPrompt: true
    });
});
```

when I do that, I see a dialog box asking to subscribe.

When I click `ALLOW`, the dialog box is dismissed but I don’t get any change of subscription through this calls (this callback is set before the call to `registerForPushNotifications`):

```
OneSignal.on('subscriptionChange', function (isSubscribed) {
    console.log('@@@@@ subscriptionChange:', isSubscribed);
    OneSignal.getUserId(function (userId) {
        console.log('@@@@@ subscriptionChange:', isSubscribed, ' userId:', userId);
        if (userId) {
            that.rabbit.registerOneSignalDevice(userId, 'web', isSubscribed, '');
        }
    });
});
```
when I use the prompt from the init method I do get the notification:

```
OneSignal.push(["init", {
    appId: “xxx”,
    autoRegister: false,
    notifyButton: {
        enable: true, /* Set to false to hide */
        position: 'bottom-right', /* Either 'bottom-left' or 'bottom-right' */
        offset: {
            bottom: '50px',
            left: '20px', /* Only applied if bottom-left */
            right: '20px' /* Only applied if bottom-right */
        }
    },
    persistNotification: false
}]);
```

and when I call init with `notifyButton.enable` set to true :

* I do receive the change of state for `subscriptionChange` when I use the notify button
* when I subscribe, through the button, and I try to subscribe from the UI (calling `OneSignal.registerForPushNotifications`), it says that I am already subscribed (expected behavior)
* but, when unsubscribed, I can call `OneSignal.registerForPushNotifications` from the UI as many times as I want and I receive no `subscriptionChange` notifications nor I see the screen telling me that I am already subscribed… which tends to prove that `OneSignal.registerForPushNotifications` doesn’t do the subscription

Is there something I need to be aware of to use `OneSignal.registerForPushNotifications`?

Thanks

Pierre

**Comment by jasonpang** [comment]
Hi Pierre,

Sorry for the delay in getting back to you. We were able to reproduce this issue and what seems to be happening is that, if you click "Unsubscribe" via the red notify button, and then you call registerForPushNotifications(), clicking Allow does nothing -- this is because you're technically subscribed but just muted from receiving notifications. Clicking Allow should "re-subscribe" you, in the same way that you'd be resubscribed by clicking back on the red notify button and clicking the red button "Subscribe".

Until we fix this issue, here's a workaround you can use:

Before calling `OneSignal.registerForPushNotifications()`, please add this code to check whether this user is manually unsubscribed. If the user is manually unsubscribed, you don't have to modal prompt them (they should resubscribe themselves by clicking the red button since that's how they unsubscribed in the first place):

`getSubscription` isn't public yet, but here's the signature:

```
/**
   * Returns a promise that resolves to false if setSubscription(false) is "in effect". Otherwise returns true.
   * This means a return value of true does not mean the user is subscribed, only that the user did not call setSubscription(false).
   * @private
   * @returns {Promise}
   */
getSubscription(callback) { ... }
```

```
var OneSignal = window.OneSignal || [];
OneSignal.push(function() {
  OneSignal.getSubscription(function(notOptedOut) {
    if (notOptedOut) {
      OneSignal.registerForPushNotifications({
        modalPrompt: true
    });
    }
  });
});
```

**Comment by pcarion** [comment]
Hi Jason, Thanks for this explanation and the workaround you are describing.

In our use case, we don't plan to use the "red button" at allas we want to have full control over the timing of when and where we present to the user a UI component to subscribe or unsubscribe.

If I read you correctly there seems to be a problem when we want to use both the red button and the `registerForPushNotifications` API, right? Do you confirm that if we use only the `registerForPushNotifications` API and setting the `enable` boolean to false in the `init` method we shouldn't have any problem?
If that's the case, is there a way to reset the state of my browser so that I can restart from _scratch_ and don't experience this API conflict?
Thanks again,

Pierre

**Comment by jasonpang** [comment]
Hi Perre,

To reset the state of your browser and test again like a new user, please follow: https://documentation.onesignal.com/docs/website-push-common-problems#clearing-your-cache-and-resetting-push-permissions

The problem you're experiencing happens when you're "unsubscribed". Actually, clicking Unsubscribe on the notify button sets a flag in our system to mute you from receiving notifications (we do this because its the most compatible option). The bug is that registerForPushNotifications() doesn't unmute the user if they're already muted. Our method `registerForPushNotificatinos()` is doing all the work to "actually" subscribe you, but because you're already actually subscribed, there is no effect or visible change.

The fix is to for us to patch the SDK to call setSubscription(true) if the user clicks Allow for the modal prompt.

If you don't use our notify button, but want to use your own UI with a way to prompt people to subscribe and allow people to unsubscribe, you'd run into the same issue when unsubscribing people. Your unsubscription will be executed by calling OneSignal.setSubscription(false), and follows the same process as the above paragraph. This method to unsubscribe users is actually what our notify button calls internally.

**Comment by jasonpang** [comment]
Fixed.

**Comment by shahzadthathal** [comment]
Same issue, please answer there.
http://stackoverflow.com/questions/40524751/onesignal-subscribe-user-through-web-page-using-web-push-sdk

**Comment by shahzadthathal** [comment]
Please let me know how I can get success or not success response using these both functions?
Actually I want to update something in database if user subscribed or unsubscribed.

OneSignal.setSubscription(true);
OneSignal.setSubscription(false);
