### ISSUE TITLE
Push notifications not working on Firefox on android

### ISSUE THREAD

**Issue by rohanjulka** [OneSignal/OneSignal-Website-SDK#148]
Hi ,
The push notifications are not working on the firefox.
It was working yesterday but somehow it has stopped working now. 

Please help.

**Comment by jasonpang** [comment]
Hi there,

Can you let us know what site we can try subscribing on and how to reproduce the issue?

**Comment by rohanjulka** [comment]
Hi ,
I cleared all the history and tried but it was not working.
I think the service was down on mozilla network's end . I also checked on other push web sites there also I wasn't able to receive push on Firefox mobile.

 Now it's working fine.

**Comment by jasonpang** [comment]
Hey there,

Actually, clearing the history on Firefox will cause you to _not_ receive notifications. Firefox has a system where if you've never visited a site, it won't show you a notification. We've confirmed that there are issues on Firefox on Android with the way it counts popup windows towards its quota, and we've reported the bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1308664.

**Comment by jasonpang** [comment]
Another user reported this issue: [Conversation](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/web-push-team/conversations/7149132410)

**Comment by jasonpang** [comment]
I think the original reason stated was actually correct, there was a history issue at the time for Firefox for Android, so this should be fixed. Will re-open / create new issue if this is reported again.
