### ISSUE TITLE
isPushNotificationsEnabled() should not include users who have muted push via setSubscription(false)

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#163]
`isPushNotificationsEnabled()` should not return false if users have muted push subscriptions. The user is registered correctly, and developers use this API to determine if a user has registered in the first place, not for determining whether the user is "completely" able to receive push.

We can have another method like `isOptedOut()` for `getSubscription()`.

**Comment by danmakenoise** [comment]
The only reason I asked to break out `isPushNotificationsEnabled` was because we needed to take separate action via the API on our end. I thought of a potential alternative.

This may be too simplified to be useful, but it could be nice to have something along the lines of the following API:

  * `isSubscribed()`: Returns a promises that resolves with a boolean indicating whether a user is registered AND unmuted.
  * `subscribe()`: If the user is registered, ensures subcription is unmuted, otherwise registers the user. Returns a promise that resolves with an object containing details of the resulting subscription state.
  * `unsubscribe()`: If a user is unregistered, does nothing, if they are registered, mutes the subscription. Returns a promise that resolves with an object containing details of the subscription state.

This would allow some really slick async code that could look like this, to make a subscription toggle that handles all scenarios:

```
  let result;

  if (await isSubscribed()) {
    result = await unsubscribe();
  } else {
    result = await subscribe();
  }
```

What the result object looks like, I don't have a strong opinion. It would be nice to be able to differentiate between `registered/unregistered` and `subscribed/unsubscribed`, so we can give different meaningful messages to the user.

**Comment by jasonpang** [comment]
This is now tracked internally.
