### ISSUE TITLE
Replace fetch with XMLHttpRequest

### ISSUE THREAD

**Issue by bmd-benita** [OneSignal/OneSignal-Website-SDK#186]
Hi OneSignal,

Some of my users use Safari browser version 10.0.2. The push notifications is running but it makes other javascript (MyMoodalBox). The console log shows this message:
```
TypeError: undefined is not a function (near '....innerHTML=n}}).send()};MoodalApp.init=f...')
open — MyMoodalBox.min.js:138
(anonymous function) — MyMoodalBox.min.js:153
e — mootools-core-1.5.0-full-compat-yc.js:3:46291
```

When I remove the OneSignal code, the MyMoodalBox works well.
And this only happen in Safari. 

Could you help me to solve this?

Thank you very much.

**Comment by jasonpang** [comment]
Hi,

Thanks for providing the log. We'd like to try and reproduce this issue; can you please provide a page URL where we can see this problem on our own Safari browser?

**Comment by bmd-bentar** [comment]
Hi Jason,

Unfortunately we removed OneSignal's service for a while on our live website page until we fix this issue. But, we can afford it on our test website page (for internal users only). So, can you send us your Public IP address then we can allow you to access the site?

**Comment by jasonpang** [comment]
Hey there,

Can you use `50.131.165.48`?

**Comment by bmd-bentar** [comment]
Can you go this site http://staging.www.bhinneka.com/products/sku01315914/asus_zenfone_2__32gb_4gb_ram___ze551ml__-_glacier_grey_silver.aspx
and click button "BELI". There was an error on console log as we said before.

**Comment by jasonpang** [comment]
Hey there,

I already got your message and link so we were able to test it out.

What's happening here is:

- Your site is using MooTools
- MooTools defines its own `Request` class, for sending network requests
- Our SDK, which depends on the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) existing, applies [whatwg/fetch's polyfill](https://github.com/whatwg/fetch), which redefines `Request` (based on the Fetch API standard for `Request`)

In the end, MooTool's definition of `Request` is being overwritten by our fetch polyfill which also redefines `Request`.

Our SDK needs to overwrite `Request` because it expects the Fetch API to exist. Safari 10 does not have the Fetch API implemented, but Safari TP (Technology Preview edition) _does have_ the Fetch API implemented.

So it's only a matter of time before Safari has its own native `Request`/`Response` class. While it is unfortunate that our polyfill is overriding something else a library is defining, I think the correct solution here is for MooTools to use a different name since both `Request` and `Response` are now standardized.

**Comment by jasonpang** [comment]
Replace the places we're calling `fetch` with `XMLHttpRequest` in the non-service worker parts of our SDK.

**Comment by bmd-bentar** [comment]
Sorry I didn't get it. So, should we wait on your development or do something on our own script? Let me know.

**Comment by jasonpang** [comment]
Sorry about the confusion, this is something we'll do on our side.

**Comment by bmd-bentar** [comment]
Oh, okay then. If SDK is updated, let us know please.. Thanks

**Comment by bmd-benita** [comment]
Hi @jasonpang, 
Could you give us estimation of the updated SDK?
Thanks.

**Comment by jasonpang** [comment]
Hi @bmd-benita,

I don't see this being fixed for at least the next month in our normal timeframe of things unfortunately.

**Comment by jkasten2** [comment]
I believe this is no longer an issue with Safari and/or MooTools. Let us know if your still seeing an issue and we can reopen. Thanks.
