### ISSUE TITLE
addListenerForNotificationOpened callback not working

### ISSUE THREAD

**Issue by moklick** [OneSignal/OneSignal-Website-SDK#188]
Hello,

I am encountering problems with the `addListenerForNotificationOpened` callback.
When I am enabling subscriptions it works whether a tab with my app origin is open or not. But it's only working once. After I clicked a notification it's only working when I don't have open tabs with the origin.
The tab gets focused but the callback is not triggered. When I then close the tab and open it again I receive the callback.

This is how I subscribe to the `addListenerForNotificationOpened` event:

```
OneSignal.push(['addListenerForNotificationOpened', notificationData => {
  console.log('Received NotificationOpened:', notificationData);
}]);
```

I am using chrome 52.0.2743.82 and firefox 48.0.2 on Linux. In both browsers I have the same problems. My workaround for now is that I listen to the messages and check if it's type `notification.clicked`:

```
navigator.serviceWorker.addEventListener('message', evt => {
  const { type, payload } = evt.data;
  if (payload && payload.length && type === 'notification.clicked') {
    console.log('Notification clicked:', payload[0]);
  }  
});
``` 

Thanks for your help.

**Comment by jasonpang** [comment]
Hey @moklick,

Do you by any chance have a publicly accessible site URL I could test this out on? Otherwise, can you let us know if:

- Are you using an HTTPS integration or our HTTP fallback integration?
  
  If notifications come from *subdomain.onesignal.com*, then you're using our HTTP integration, otherwise if notifications come from *yourdomain.com* then you're using an HTTPS integration.

- Are you using `notificationClickHandlerOrigin`?

  If you are, you would see this in your JavaScript init options.

I haven't looked into this yet, but it might be related to https://github.com/OneSignal/OneSignal-Website-SDK/issues/185 which is a bug in our SDK.

**Comment by moklick** [comment]
Hey @jasonpang,

thanks for your fast response. We are only using HTTPS. I am testing this with localhost and `allowLocalhostAsSecureOrigin:true`. I tested it with `notificationClickHandlerOrigin:'origin'` and without that option. I will see If I can setup a demo page.

**Comment by TroyCoombs** [comment]
Any update on this?

**Comment by jasonpang** [comment]
Hey @TroyCoombs @moklick,

Based on @moklick's description, what's happening here is that `addListenerForNotificationOpened` is intentionally only calling the callback once, and not every time a notification is clicked. Unfortunately, this was poorly documented so it wasn't clear. The documentation has been updated now to mention this.

This explains why @moklick mentioned:
- It only worked once for him, and
- After working once, it only worked when he didn't have open tabs with the origin. Because, if this happens, we store the event, wait for a new window to be opened from the notification, check for any stored events, find the stored event and fire it.

@moklick, sorry you went through the trouble of testing all that.

For now, to have your callback fired whenever a notification is clicked not just once, but every time, please call `addListenerForNotificationOpened()` after the callback to `addListenerForNotificationOpened()`.

**Comment by TroyCoombs** [comment]
Thanks @jasonpang, very helpful.  how would this look?  here's the current code
OneSignal.push(["addListenerForNotificationOpened", function (data) {
                var scope = angular.element(document.getElementsByTagName("md-sidenav")[0]).scope();
                var conversationId = /[^/]*$/.exec(data.url)[0];
                scope.$state.go('conversations.conversation', { conversationId: conversationId, member: null });
            }]);

**Comment by moklick** [comment]
thanks for the update @jasonpang

**Comment by farhan687** [comment]
Hey @jasonpang @moklick 

I am facing same issue and I never reach to callback **Not even once** but whenever I refresh the page only then `addListenerForNotificationOpened` callback is executed.

I am using following code:

I have created test app, I can give you credentials.

```js
var OneSignal = window.OneSignal || [];
    OneSignal.push(["init", {
      appId: "*****",
      subdomainName: '****',
      autoRegister: true, /* Set to true to automatically prompt visitors */
      httpPermissionRequest: {
        enable: true,
      },
      notifyButton: {
        enable: true, /* Set to false to hide */
      },
      notificationClickHandlerMatch: 'origin',
      notificationClickHandlerAction: 'focus',
    }]);

    function notifListen() {
      OneSignal.push(['addListenerForNotificationOpened', notificationData => {
        console.log('Received NotificationOpened:', notificationData);
        notifListen();
      }]);
    }

    notifListen();
```


I am sending only header and message while pushing the notification.

Did I miss anything?

Let me know if you need appId and REST API key.

**Comment by jasonpang** [comment]
Hey there,

I wasn't able to reproduce this issue. Make sure the URL you're sending matches the same origin as your site (this means the URL must match the beginning protocol of your site like http:// or https://). Message us at support@onesignal.com with a test page on your site and the URL you're using for the notification if you're still having trouble.

**Comment by rluckez** [comment]
Hi @jasonpang,
I'm facing the issue @moklick describe above, even if i call addListenerForNotificationOpened inside my callback, it just fire once and in a new tab.
I'm using notificationClickHandlerMatch: 'origin' and  notificationClickHandlerAction: 'focus'.
I click on notification, tab does get focus, but i do not get notification event.
Am i missing something?

**Comment by joaoedezio** [comment]
Hi @rluckez did you find a solution, I have the same issue here.

**Comment by rossPatton** [comment]
@jasonpang  Can we get a working code example for triggering the click event right away? I've tried to do what was suggested, but it's really unclear what your solution looks like. It might also be helpful to add this solution to the docs - I ended up here because I need to generate dynamic url strings for utm params, and `addListenerForNotificationOpened` was the suggested solution

**Comment by jasonpang** [comment]
Hey @rossPatton, can you clarify what you're trying to do? Generating a dynamic UTM param shouldn't be related to `addListenerForNotificationOpened`. What behavior are you looking for? The callback to `addListenerForNotificationOpened` should fire the moment the notification is clicked.

**Comment by zaidsallam** [comment]
CAN ANYONE GIVE ME THE SOLUTION I FACED THIS PROBLEM BUT I CAN'T FIND THE FIGHT SOL ...PLEASE HELP ME  !!! I FACE THE TERMINATION

**Comment by matteomartinelli** [comment]
Having this issue too, any solution?

**Comment by luisfprj** [comment]
I'm facing this problem too, someone has already solved?
I want that every push clicked the addListenerForNotificationOpened fire the event, but it only fire once and only when my tab is closed.    ( 'origin' and 'focus').

because I want to get the additionalData from push and do some stuff to redirect to a deeplink direct to a "product".

when the tab is closed it work properly well.
when the tab is already opened the event is not fired.

**Comment by meghna-fishbowl** [comment]
Any updates? How can we fix this problem. We get callback just once if we close the browser.

**Comment by toanhuynh345** [comment]
use HTTPS in your domain, don't use HTTP. that's work. :D
