### ISSUE TITLE
OneSignal is working fine on Mozilla Firefox and Safari but it does not work on Chrome.

### ISSUE THREAD

**Issue by harlanecastro** [OneSignal/OneSignal-Website-SDK#190]
We no longer know what to do to make OneSignal work in Google Chrome. It works fine on Mozilla Firefox and Safari but does not work on Chrome.

We implemented OneSignal in clean HTML to rule out possible incompatibilities with other scripts, but the problem persists. Look: https://www.cliqueiachei.com.br/onesignal.htm

We also hired an SSL for the subdomain. See too: https://meusanuncios.cliqueiachei.com.br/onesignal.htm

No matter how many times I click the button, it never saves. We need help, we do not know what else to do.

**Comment by jasonpang** [comment]
Hi there,

Since this isn't likely to be a web SDK issue (usually the issues are setup-related), please first ask on our support channel at onesignal.com (also log in to your account before starting up our live chat, as it allows us to see your linked sites/apps and more quickly get back to you). You can click the bright red button at the bottom right of our home page.

---

It looks like the manifest.json is being declared on the site origin **https://cliqueiachei.com.br**:

```html
<link rel="manifest" href="https://cliqueiachei.com.br/manifest.json">
```

but the site origin you're loading is **https://www.cliqueiachei.com.br** (extra www.).

For web push, the manifest.json must be referenced from the same origin that users are visiting from. The browser treats the extra `www.` as a completely separate origin.

Also, any time the origin changes, push permissions and web storage and cookies are all completely separated, so you don't want your site visitors to subscribe twice on https://cliqueiachei.com.br and https://www.cliqueiachei.com.br.

The best solution here is to make https://cliqueiachei.com.br --> redirect to --> https://www.cliqueiachei.com.br. Or, alternatively, make https://www.cliqueiachei.com.br --> redirect to --> https://cliqueiachei.com.br.
