### ISSUE TITLE
Not work on Firefox 50.1.0

### ISSUE THREAD

**Issue by lissdy** [OneSignal/OneSignal-Website-SDK#193]
Got this error on Firefox 50.1.0

"OneSignal: IndexedDb web storage is not available on this origin since this profile's IndexedDb schema has been upgraded in a newer version of Firefox. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1236557#c6"

**Comment by jasonpang** [comment]
Hi @lissdy,

If you're using Firefox's Private Browsing Mode, please use the normal Firefox browsing mode to test push notifications.

Otherwise, it looks like you're affected by the linked bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1236557#c6). This is an intentional Firefox design, and the only solution I believe is to refresh your Firefox profile. 

To refresh your Firefox profile, visit the URL "about:support" (this is an internal Firefox page), and then click "Refresh Firefox..." on the top right.

In the future, can you please ask these questions first on our chat support at onesignal.com (red button on the bottom right). It allows us to get to you faster and better organize our conversations here. We'd just like to keep this Issues section for web SDK bugs and features.
