### ISSUE TITLE
Cannot use custom service worker file name

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#212]
These two places hardcode "OneSignalSDKWorker", which prevents clients from being able to use a custom-named service worker file.

- https://github.com/OneSignal/OneSignal-Website-SDK/blob/d790181d7b8f50bf497e894b1a934a7471f85d29/src/helpers/ServiceWorkerHelper.ts#L161
- https://github.com/OneSignal/OneSignal-Website-SDK/blob/a863bd1bed759b456b6500b219831a764232267a/src/service-worker/ServiceWorker.ts#L656

**Comment by iainjp** [comment]
Hi Jason,

My colleague Andy and I have been looking into this. We believe one solution could be to enforce a naming convention on the OneSignalSDKWorker and OneSignalSDKWorkerUpdater files. This naming convention could be that their names must **contain** "OneSignalSDKWorker" and "OneSignalSDKWorkerUpdater" respectively, but do not need to **exactly match** "OneSignalSDKWorker.js" and "OneSignalSDKUpdaterWorker.js".

This benefits from the ability to add a hash to the name in order to break any caches during static asset deployments. 

The changes required for the above would be:
 - removing the file extension and inverting the condition in ServiceWorker.ts, such as below

```
if (contains((self as any).location.pathname, "OneSignalSDKWorkerUpdater"))
      var serviceWorkerVersionType = 'WORKER2_ONE_SIGNAL_SW_VERSION';
    else
      var serviceWorkerVersionType = 'WORKER1_ONE_SIGNAL_SW_VERSION';
```

This would require no changes to ServiceWorkerHelper.ts, as this already does a `contains` check without the file extension.

Let me know what you think. This isn't quite a custom-named service worker solution, but does provide more flexibility.

**Comment by jasonpang** [comment]
Hey @iainjp,

Sorry for the late reply, and thanks very much for spending the time to look into this and suggest that solution. 

Turns out the original code worked, but doesn't work as well as with this fix.

Fixed by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/533c32c536c3fbd098ca232eb5707b96aa1d4c3d.
