### ISSUE TITLE
Sending notification to user at a fixed time everyday?

### ISSUE THREAD

**Issue by SethuSenthil** [OneSignal/OneSignal-Website-SDK#245]
I want to send a notification to the user at a set time every day, without manually creating a new notification. I know the autonomous feature but it doesn't allow me to send the same notification every day or at a fixed time (to all users).

**Comment by gdeglin** [comment]
OneSignal provides an integration with Zapier for a few features, including daily or weekly recurring notifications. You can find more details here https://documentation.onesignal.com/v3.0/docs/zapier

Since this is a product question and not an SDK issue, please follow up with us at support@onesignal.com if you need any more assistance with this.
