### ISSUE TITLE
Is possible create segment manual with script? javascript or php?

### ISSUE THREAD

**Issue by rmdevelopers** [OneSignal/OneSignal-Website-SDK#256]
I would like to know if it is possible to create segments and conditions via javascript or PHP.

**Comment by gdeglin** [comment]
Segments can only be created and edited on the dashboard. But our notification creation API lets you put in a list of whatever filters you'd like to target users, so you can use that instead of segments. 

This issue tracker is for SDK bugs, so please follow up with us at support@onesignal.com if we can help with this further. Thanks!
