### ISSUE TITLE
Opening a window on notification click event, addListenerForNotificationOpened not firing

### ISSUE THREAD

**Issue by natterstefan** [OneSignal/OneSignal-Website-SDK#283]
I tested it on localhost, on a domain (w/ and w/o https) and on your [HttpWebPushDemo](https://onesignal.github.io/HttpWebPushDemo/) and got the same result on all of them:

- I subscribe successfully
- I sent myself a Notification
- Click on it _and_ then it _does not_ open the url specified in the Notification. (Also tested with a Request via Postman)

**Problem**
- Browser does not open desired URL

**Tested on**
- Chrome (Version 62.0.3202.94)
- Firefox (Version 57.0)

**Links**
- https://onesignal.github.io/HttpWebPushDemo/
- https://documentation.onesignal.com/v3.0/docs/web-push-sdk#section-receiving-notifications

**Comment by jasonpang** [comment]
Hi @natterstefan,

I'm not able to reproduce this issue. Would you be able to post the cURL command of the notification request you made here (without your REST API key)?

If you're setting the "url" property when sending a notification, the following special cases might be happening:

- Any URL with `_osp=do_not_open` anywhere as part of the string will not open any URLs or focus any existing tab on Chrome and Firefox (Safari always opens a URL).
- If a browser tab/window with the exact same URL as the notification's URL exists, that tab should be focused instead of a new tab being opened. Otherwise, a new browser tab/window should be opened to your notification's URL.
- There are some JavaScript SDK initialization parameters `notificationClickHandlerMatch` and `notificationClickHandlerAction` that affect notification click behavior if you have them set.

**Comment by natterstefan** [comment]
Hi @jasonpang 

> There are some JavaScript SDK initialization parameters notificationClickHandlerMatch and notificationClickHandlerAction that affect notification click behavior if you have them set.

This could probably help me to solve an issue. I have the following setup/scenario:

- the website is running on `https://sub.example.com`
- in the OneSignal App (your Dashboard) I have set the url to `https://sub.example.com`
- in the index.html.tpl (of my project) I set the [defaultNotificationUrl](https://documentation.onesignal.com/docs/web-push-sdk#section--setdefaultnotificationurl-) to `https://sub.example.com/folder`
- _but_ the `https://sub.example.com/folder` will redirect to either `https://sub.example.com/folder/role-1` or `https://sub.example.com/folder/role-2` (in relation to your logged in user's role).
- I cannot use `https://example.com` as the base url, because this is just an entry point for the other "services" and "subsites", with a completely different setup/technology/etc.

My current situation is now:

- I get and see the [`notificationDisplay` event](https://documentation.onesignal.com/docs/web-push-sdk#section-notification-display) in an already opened tab of the website
- _but_ I do not see the [`addListenerForNotificationOpened`](https://documentation.onesignal.com/docs/web-push-sdk#section--addlistenerfornotificationopened-) one. Probably because the defaultUrl and the Url the user is redirected to is different.
- As a side note: we are currently trying to avoid setting the `url` attribute in the request to target both Android (app) and Web. As Android would open the browser instead of the app (if `url` is set) we are just using the `data` property (including data to create the final url). If I set the `url` attribute it works... But still I would not be able to get the additional `data` attributes I guess...

My current problem:

- I see that the user gets a notification, _but_ I cannot handle the Click! Probably because of the redirect (final url and default url differ) or for some other reason I do not see yet.

Btw, I have not played around with the [`notificationClickHandlerMatch` or `notificationClickHandlerAction`](https://documentation.onesignal.com/docs/web-push-sdk#section--addlistenerfornotificationopened-) yet.

Can you help me out with that one please?

**Comment by natterstefan** [comment]
Just for the record, we do now send 2 API calls from the backend. One for mobile phones (with no `url` property) and one with `url` for the web (with the full url, so that the Frontend does not need to handle the `data` from the payload itself).

**Comment by jasonpang** [comment]
It sounds like by sending 2 separate notifications for mobile and web, the mobile-only notification has no `url` and opens a page in your app instead of the browser, while the web-only notification uses `url` to avoid any issues with being unable to open a window when custom handling the notification click yourself. This is the workaround you've adopted.

Previously, it sounds like you were trying to handle the notification click event to open your own URL by reading the additional `data` property of the notification and opening a custom URL you set for yourself, but you were _not_ receiving any callback to `addListenerForNotificationOpened()`, and so were never given the option to handle the callback to open a URL.

From [docs](https://documentation.onesignal.com/docs/web-push-sdk#section--addlistenerfornotificationopened-):

> The default behavior:
> 
> Events only fire if your URL matches the notification's opening URL exactly; the event will be available on the newly opened tab (and only that opened tab) to the notification's opening URL. See the special flags notificationClickHandlerMatch: origin and notificationClickHandlerAction: focus for different use cases.

So `addListenerForNotificationOpened()` will only fire if:
  - The URL to open ("launch URL") exactly matches an existing browser tab, if `notificationClickHandlerMatch` is not set
  - Any existing browser tab is open to `https://sub.example.com`, if `notificationClickHandlerMatch` is set to `origin`

The URL to open ("launch URL") when clicking the notification is:
  - The notification's URL if one exists (it doesn't)
  - Then the default notification set by `setDefaultNotificationUrl()` (this was set to `https://sub.example.com/folder`)
  - Or if neither of the above, the service worker's registration scope (case doesn't apply here, but this is `https://sub.example.com`)

So the launch URL is `https://sub.example.com/folder`. If your page was open to `https://sub.example.com`, you should have received the `addListenerForNotificationOpened()` event. Alternatively, you could just set `notificationClickHandlerMatch: origin` and have a browser tab open to any page of `https://sub.example.com`, including the home page.

Aside from all this, I don't know if you'd be able to open a new browser tab from `addListenerForNotificationOpened()`. Our event is custom and not considered a direct result of a user's action, and probably won't give you the privileges to open a new window. You would have to implement the `push` event in the service worker to open a new window, and we would first have to support overriding our `push` event with a custom `push` event first.

**Comment by cedrouck** [comment]
@jasonpang :
Try this (it works perfectly for me) :

```
      const process = (payload) =>  {
          console.log('Notification clicked', payload });
          // add anything you want here
      }
      const handler = (payload) =>  {
          // your custom method
          process(payload);
          // add new handler attach for next notifications
          OneSignal.addListenerForNotificationOpened(handler);
      };
      // first handler attach for the first notification
      OneSignal.addListenerForNotificationOpened(handler);

```

or with OneSignal.push :

```
      const process = (payload) =>  {
          console.log('Notification clicked', payload });
          // add anything you want here
      }
      const handler = (payload) =>  {
          // your custom method
          process(payload);
          // add new handler attach for next notifications
          OneSignal.push(["addListenerForNotificationOpened", handler]);
      };
      // first handler attach for the first notification
      OneSignal.push(["addListenerForNotificationOpened", handler]);
```

Hope this will help someone.
