### ISSUE TITLE
Solve "NoDeviceId" NotSubscribedError

### ISSUE THREAD

**Issue by natterstefan** [OneSignal/OneSignal-Website-SDK#285]
How can I solve this? Clearing the cache, indexedDB and local storage does not solve it. What am I missing?

```
NotSubscribedError {reason: "NoDeviceId", message: "This operation can only be performed after the user is subscribed.", name: "NotSubscribedError", stack: "NotSubscribedError: This operation can only be per…m/sdks/OneSignalSDK.js:1:1460)↵    at <anonymous>"}
```

Chrome: latest
OneSignalSDK: latest WebSDK (from your cdn)

Edit: pasting the following (from your [documentation](https://documentation.onesignal.com/v3.0/docs/troubleshooting-web-push#section-3-check-if-you-are-subscribed)) into my console

```js
function isPushNotificationsEnabledVerbose() {
    console.log('isPushNotificationsEnabledVerbose()');
    Promise.all([
            OneSignal.isPushNotificationsEnabled(),
            OneSignal.getUserId(),
            OneSignal.getRegistrationId(),
            OneSignal.getNotificationPermission(),
            OneSignal.isOptedOut(),
            navigator.serviceWorker && navigator.serviceWorker.controller && navigator.serviceWorker.controller.scriptURL.indexOf('OneSignalSDKWorker.js') !== -1
        ])
        .then(([isSubscribed, userId, registrationId, notificationPermission, optedOut, serviceWorkerActive]) => {
            console.log('Is Completely Subscribed:', isSubscribed);
            console.log('');
            console.log('What is our OneSignal user ID?', userId);
            console.log('What is our push subscription token?', registrationId);
            console.log('What is the notification permission status?', notificationPermission);
            console.log('Are you manually opted out?', optedOut);
            console.log('Is a service worker registered and active? (should be false on Safari)', serviceWorkerActive);
            console.log('What is the current URL of this page?', location.href);
            console.log("What environment does OneSignal think it's in?", OneSignal.environment.getEnv());
        })
        .catch(e => {
            log.error("Issue determining whether push is enabled:", e);
            reject(e);
        });
}
isPushNotificationsEnabledVerbose();
```

just returns: 

```
undefined
What is our OneSignal user ID? null
What environment does OneSignal think it's in? 
```

Then it stops...

**Comment by jasonpang** [comment]
Hi @natterstefan,

You might get the above error if you're calling `getTags()`, `setSubscription()`, or `sendSelfNotification()`.

If you're not getting a stack trace and it's being printed instead of thrown as an actual error, it's probably from `getTags()`.

You can fix this issue by using `isPushNotificationsEnabled()` before using these methods.

**Comment by natterstefan** [comment]
@jasonpang Hello, thanks for the answer. This may be related to the [localhost-issue](https://github.com/OneSignal/OneSignal-Website-SDK/issues/281), but `isPushNotificationsEnabled()` always returns false, even though I get notifications and see my player in the App Dashboard. Do you think this is because of the localhost again?

**Comment by jasonpang** [comment]
Hi @natterstefan,

Sorry for the delay in getting back to you.

There's an [updated script here](https://documentation.onesignal.com/docs/troubleshooting-web-push#section-3-check-if-you-are-subscribed). Does running this new script also only return two lines (what is user ID / what environment does OneSignal think it's in)? There should be at least 7 lines of output.

If you're getting a null OneSignal user ID, that just means that the ID we stored as a copy after a successfully push subscription was erased, but it's just the copy of the ID that's erased, and it doesn't actually impact your ability to receive push notifications. The real ID is still on the dashboard that you can see.

But if you are seeing a null user ID, IndexedDB, which is where we store the user ID, was somehow erased, and that will cause isPushNotificationsEnabled() to return false, because it looks up the stored copy of the ID to see if it exists.

Anytime IndexedDB is cleared, isPushNotificationsEnabled() will return false. If you see that ...

- The new verbose script returns a null user ID, and a null registration ID, but with a valid push registration, with a granted permission state, and that you're not opted out, then isPushNotificationsEnabled() is returning false because IndexedDb storage was cleared. The actual push subscription isn't affected at all, but the components used for determining whether push is enabled is affected. This isn't great because, depending on the environment, a user might get prompted again when they really are subscribed. For testing, clearing data is okay, but you just have to be aware that you might see you're not subscribed (like you're seeing now).

**Comment by jwilm** [comment]
Hey @natterstefan, please let us know if you've resolved this.
