### ISSUE TITLE
Send notification to my website

### ISSUE THREAD

**Issue by Gone4Coding** [OneSignal/OneSignal-Website-SDK#288]
Hi everyone,

I have a question, and I think a dumb one. But I really want to clarify the situation.
I configured my website in OneSignal and I was wondering if I could send a notification from my android app to my website, like inverting the papers of sending a notification to the app.

I've already searched it and couldn't find any relevant information.
If someone could clarify this I would be very thankful.

Thank you anyway.

**Comment by jasonpang** [comment]
Hi @Gone4Coding,

Sorry for the delay in getting back to you.

If you're using OneSignal, you could pretend to do this by issuing an API call from your Android app to OneSignal, so that OneSignal sends notifications to your website.

Website push notifications are displayed when a subscriber's Chrome / Firefox browser, which is connected to its push service (FCM for Google Chrome, Firefox's push server for Firefox), receives a message from that push service for a new notification. One of the advantages of this infrastructure of push notifications is being able to take advantage of that persistent connection.

So if you wanted to send from your Android app to your website, you would really be finding a way to ask Google to deliver a message to your Chrome on Android users, and ask Firefox to deliver a message to your Firefox on Android users. There are many ways of doing that (e.g. using our service, or interfacing with Google / Firefox's push servers directly), but I think that's generally the path you want to explore.

Otherwise, a website would have to develop its own message infrastructure and open a socket connection to your own server, and your Android app would have to send a message to your server to be passed to your website, which bypasses built-in push notifications.

**Comment by jwilm** [comment]
It looks like this was resolved. Please feel free to reopen if not.
