### ISSUE TITLE
getNotificationPermission returns only "default" and "granted", not "denied"

### ISSUE THREAD

**Issue by amankapoor** [OneSignal/OneSignal-Website-SDK#289]
Hello,

Refer to https://documentation.onesignal.com/docs/web-push-sdk#section--getnotificationpermission-

It says `getNotificationPermission` can return "default", "granted", "denied", but while implementing it I never get a "denied" response. This also affects `notificationPermissionChange`.

Please take a look. You might want to change the docs, or code.

This is the code I am writing, you may try implementing it on your machine.

```
OneSignal.push(function() {
        OneSignal.isPushNotificationsEnabled(function(isEnabled) {
            if (isEnabled) {
                OneSignal.push(["getNotificationPermission", function(permission) {
                    console.log("Site Notification Permission:", permission);
                    // three cases here
                    if (permission === "default") {
                        $('#notifStatus').text("true " + permission)  
                    } else if (permission === "denied") {
                        $('#notifStatus').text("true " + permission)  
                    } else {
                        $('#notifStatus').text("true " + permission)
                    }
                }]);
            } else {
                // three cases here
                OneSignal.push(["getNotificationPermission", function(permission) {
                    console.log("Site Notification Permission:", permission);
                    // three cases here
                    if (permission === "default") {
                        $('#notifStatus').text("false " + permission)  
                    } else if (permission === "denied") {
                        $('#notifStatus').text("false " + permission)  
                    } else {
                        $('#notifStatus').text("false " + permission)
                    }
                }]);
            }
        });
    });
```

**Comment by amankapoor** [comment]
Ohh, I forgot to add that this issue exists in Chrome. On Firefox, I can see denied. I don't have access to Safari, so no idea about it.

**Comment by jasonpang** [comment]
Hey @amankapoor,

Sorry for the delay in getting back to you.

Due to recent changes in Chrome 62's permission API, we can no longer accurately detect a user's permission for HTTP sites or within a cross-origin iframe. The [first section of this pull request](https://github.com/ampproject/amphtml/pull/11480) explains the changes in more detail.

The link above describes permission changes for cross-origin iframes, but for non-iframes regular HTTP sites, the permission change is simpler but a little more drastic: the permission is always denied. It doesn't matter if you've granted permissions, denied permissions, or never been prompted -- `Notification.permission` will always return `denied`.

To solve this, our workaround is to assume the permission is `default` until we know for sure it is either `granted` or `denied`.

What this means is we treat always assume `default` until the popup window to subscribe appears. The moment it does, we have access to the true permission state (the popup window is HTTPS, and is its own top-level frame and so has access to the real permission state), and we can store a storage flag to mark our real permission state to return next time.
