### ISSUE TITLE
Safari bug undefined is not an object (evaluating 'navigator.serviceWorker.getRegistration')

### ISSUE THREAD

**Issue by sido420** [OneSignal/OneSignal-Website-SDK#295]
I noticed this error in Safari only (FF and Chrome are fine).

```
[Error] TypeError: undefined is not an object (evaluating 'navigator.serviceWorker.getRegistration')
```
heres the relevant code snippet
```
            OneSignal.push(function() {
                App.PushSupported = OneSignal.isPushNotificationsSupported();
                if (App.PushSupported) {
                    console.log('is Push supported? ' + App.PushSupported);
                    navigator.serviceWorker.getRegistration()   //<== err line
                        .then(function(reg) { console.log(reg);  });
                }
                ....
```

**Comment by sido420** [comment]
Updates on this? 
https://domain.com/OneSignalSDKWorker.js is the location of service worker (accessible through Safari).

```
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');
```

**Comment by jasonpang** [comment]
Hi there,

`App.PushSupported` will return true because Safari supports push notifications, but does not support the standardized W3C push notifications that `navigator.serviceWorker.getRegistration()` relies on.

Please first check for `typeof navigator.serviceWorker === "undefined` before the `getRegistration()` call, and that should fix it.
