### ISSUE TITLE
Notification Bell Won't Show Up With www In The Domain

### ISSUE THREAD

**Issue by BrianMoreno1994** [OneSignal/OneSignal-Website-SDK#302]
Hi, so I have a question. I have a domain, let's say _http://example.com_. Whenever I go to this website the notification bell shows up, but when I go to _http://www.example.com_ the notification bell won't show up and I get this in the console:

```
reason: "WrongSiteUrl"
message: "OneSignal: This web push config can only be used on http://example.com. Your current origin is http://www.example.com."
stack: "SdkInitError: OneSignal: This web push config can only be used on http://example.com. Your current origin is http://www.example.com.
```
 
Why won't the notification bell show up?

**Comment by gdeglin** [comment]
Browsers expect push notification permissions to be tied to a single domain, and the https://example.com version of your website is considered a different domain than https://www.example.com. In order to prevent users from having double subscriptions, you may only prompt for push permission on one of those.

We recommend redirecting any traffic to one version to the other version. 

You can learn more about this limitation in the note at the bottom of this page: https://documentation.onesignal.com/docs/web-push-complex-integrations
