### ISSUE TITLE
Custom service worker push handler

### ISSUE THREAD

**Issue by slashsBin** [OneSignal/OneSignal-Website-SDK#306]
Hi all,
In order to listen to push notifications(for example to hide them #304 or run some custom code #52), which is currently not yet supported officially by OneSignal, led some users to use difficult workarounds #85.

This issue is an attempt to demonstrate one of such workarounds, hoping to be any help to upstream implementation by OneSignal, and also achieve a good temporary workaround with the help of the OneSignal community.

These two steps are how we are doing it:

1. In the `OneSignalSDKWorker.js` file, we change it to:
```js
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');

// Remove SDK push handler
self.removeEventListener('push', self.OneSignalWorker.onPushReceived);
// Register our own custom handler
self.addEventListener('push', function (event) {
    if (event.data) {
        const data = event.data.json();
        const notification = self.OneSignalWorker.buildStructuredNotificationObject(data);
        console.log('Notification Received:');
        console.table(notification);

        // Do Something Custom with the Notification
        // ...

        // If we want to communicate with the Page:
        // we define a custom event with custom payload
        self.OneSignalWorker.workerMessenger.broadcast('myCustomEvent', {
            a: 1,
            b: 2
        });

        // If we want to show the notification,
        // we call the original SDK push handler
        if (true) {
            self.OneSignalWorker.onPushReceived(data);
        }
    }
});
```

2. In the Page:
```js
(function (window) {
    let OneSignal = window.OneSignal || [];

    // Send Custom Tags
    let OneSignalTags = {
        user_id: '',
        user_type: ''
    };
    const jwt = window.parseJwt(localStorage.getItem('jwtToken'));
    if (typeof jwt.sub !== 'undefined' && typeof jwt.aud !== 'undefined') {
        OneSignalTags.user_id = jwt.sub;
        OneSignalTags.user_type = jwt.aud;
    }
    OneSignal.push(['sendTags', OneSignalTags]);


    OneSignal.push(function () {
        // Initialize
        OneSignal.init({
            appId: window.OneSignal_app_id
        });

        // Register our own custom event handler
        OneSignal.isPushNotificationsEnabled().then(function (isEnabled) {
            if (isEnabled) {
                console.log('Push notifications are enabled!');
                OneSignal.context.workerMessenger.on('myCustomEvent', function (data) {
                    console.log('recieved from service worker:');
                    console.table(data);
                });
            } else {
                console.log('Push notifications are not enabled yet.');
            }
        });
    });
})(window);
```

Any suggestions or tunning is really appreciated.

**Comment by jasonpang** [comment]
Thanks for contributing @slashsBin!

If someone does end up using this code, please be aware of using non-public methods that can change at any time. For example, `self.OneSignalWorker.onPushReceived`, `self.OneSignalWorker.buildStructuredNotificationObject`, `self.OneSignalWorker.workerMessenger.broadcast`, and `OneSignal.context.x` might not be available at any time since it's not a publicly supported API.

Also, at least for Chrome, the browser only allows suppressing a visible notification if your page is the active tab, otherwise the browser provides a limited budget of invisible notifications (so frequent background updates aren't really possible yet).

In the future, a publicly supported hook that provides a structured notification object (the object that comes in the `push` event has abbreviated keys) would be the general solution, but we don't have support for that yet.

We'll internally triage service worker hooks as a feature request and close this issue.

**Comment by alipajand** [comment]
Any updates and new features?
