### ISSUE TITLE
Installing a custom service worker alongside OneSignal service worker

### ISSUE THREAD

**Issue by manikantachalla** [OneSignal/OneSignal-Website-SDK#310]
I am trying to subscribe the user with below code. I can't see the user getting subscribed to one signal dashboard even if the user grants the permission through browsers permission prompt.
```
var OneSignal = window.OneSignal || []
OneSignal.init({
    appId: xxx,
    autoRegister: false,
    notifyButton: {
        enable: false
    },
    welcomeNotification: {
        "title": "Welcome",
        "message": "Thanks for subscribing!",
    }
})
OneSignal.on('subscriptionChange', function (isSubscribed) {
    console.log("The user's subscription state is now: " + isSubscribed)
})
OneSignal.on('notificationPermissionChange', function (permissionChange) {
    OneSignal.setSubscription(true)
});
```
Am I doing something wrong?

**Comment by jasonpang** [comment]
Are you seeing:

> The user's subscription state is now: true

You can turn on logging by following [steps 1 and 2 here](https://documentation.onesignal.com/docs/troubleshooting-web-push#section-debugging-using-browser-developer-tools).

**Comment by manikantachalla** [comment]
I can't see the line `The user's subscription state is now: true` in my logs. But i am sure that the event notificationPermissionChange is getting triggered.

**Comment by jasonpang** [comment]
Hey @Dante-101,

Sorry for the late reply.

- The service worker's location is `undefined/undefined?appId=...`, which is incorrect. I checked your app's settings, and you're currently using our `Typical Site` setup and you have enabled `Customize service worker paths and filenames` with what looks like the correct settings. Are you still getting `undefined/undefined?appId=...` for the service worker registration URL with these settings currently? I'm checking 13 days later so I'm not sure if this is a problem anymore.

- If our service worker is registered to a scope that isn't visited by the current page visitor during subscription, our web SDK will halt after installing the service worker. This is because our SDK waits for the page to fire an event notifying us a service worker has taken control of the page. We strongly recommend installing the service worker to the root scope of the page (`/`) to allow visitors browsing any page to subscribe to notifications, not just visitors who browser `/at-home/xxx`.

- Because only one service worker can be registered per-scope, we recommend merging service workers. Please see [this section of our documentation](https://documentation.onesignal.com/docs/web-push-setup-faq#section-can-onesignal-integrate-with-another-service-worker-on-my-site-or-a-progressive-web-app-) for more information.

**Comment by jasonpang** [comment]
Merging service workers should be the solution. Please feel free to leave a comment if there's a new issue you discovered. If you're having trouble with the exact syntax, please reach out to us at support@onesignal.com.

**Comment by nasr18** [comment]
@jasonpang I'm getting the same error as
```Failed to register/update a ServiceWorker for scope ‘https://dev.tmmmt.com/’: Bad Content-Type of ‘text/html’ received for script ‘https://dev.tmmmt.com/OneSignalSDKWorker.js?appId=########’. Must be ‘text/javascript’, ‘application/x-javascript’, or ‘application/javascript’.```

Any help would be really appreciated.
