### ISSUE TITLE
CSP error message on FireFox 

### ISSUE THREAD

**Issue by sido420** [OneSignal/OneSignal-Website-SDK#314]
I'm getting the following error on FF.
```
Content Security Policy: The page’s settings blocked the loading of a resource at https://example.com/OneSignalSDKWorker.js (“child-src https://img.youtube.com https://www.youtube.com https://youtube.com https://player.vimeo.com/ https://www.dailymotion.com/ https://player.twitch.tv/ https://coub.com/ https://player.youku.com/ https://scratch.mit.edu/ https://w.soundcloud.com/”).
```
The page has embeds from those websites mentioned above. And, I do not see the video players being embedded on the page.

The URL contains following:
```
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');
```

**Comment by jasonpang** [comment]
@sido420,

Do you happen to have a URL to the page we can visit to reproduce this issue?

**Comment by sido420** [comment]
No, not public.

I will try to reproduce and get back to you.

**Comment by jasonpang** [comment]
Hi @sido420,

I think you'll need to append `https://cdn.onesignal.com/` to your `child-src` whitelist.

It looks like `child-src` determines accepted sources for web workers, and it's probably affecting `importScripts()`.

Can you let us know if that works?

**Comment by jasonpang** [comment]
Hi @sido420,

Can you clarify whether the URL you're receiving the Content Security Policy error on is:

a) The service worker script itself (e.g. https://your-site.com/OneSignalSDKWorker.js)
b) One of the pages on your site (e.g. https://your-site.com or https://your-site.com/some-page)

For **a)**:

According to MDN, service workers are not governed by the Content Security Policy of their parent page but instead by the Content-Security-Policy header passed to the response of https://your-site.com/OneSignalSDKWorker.js.

Can you provide the `Content-Security-Policy` header value for your service worker script? If you're sending notifications with an HTTP URL, you may need to allow for our HTTPS image proxying service. If you're using webhooks, you'll need to modify your CSP to allow for the webhook host. You'll probably also need to modify your CSP to allow onesignal.com because we report notification clicks.

For **b)**:

We'll need more details on what resource was blocked from loading. Currently, our SDK should only be loading resources from onesignal.com.

**Comment by jasonpang** [comment]
Please leave a comment when you have more details, but in the meantime I'm going to close the thread for inactivity.

**Comment by NicoPennec** [comment]
in addition, my CSP configuration for OneSignal:

```
content-security-policy:

script-src 'self' https://cdn.onesignal.com https://onesignal.com;
connect-src 'self' onesignal.com;
```

**Comment by jasonpang** [comment]
Hi @NicoPennec,

Can you please provide the following details?

- What URL are you getting this CSP error on?
- What is the exact CSP error message?

**Comment by NicoPennec** [comment]
Sorry, it's not an error :)

I just wanted to share my complete CSP config that works with OneSignal, because your previous response is incomplete.

**Comment by crustamet** [comment]
OneSignal should comunicate trough the https interface and not load scripts after scripts and files inline.
I will not use this, for my security purposes.

**Comment by kristofer-lp8f** [comment]
For anyone looking for a complete list, this worked for me:
```
script-src 'self' https://cdn.onesignal.com/ onesignal.com/;
child-src 'self' https://cdn.onesignal.com/ https://onesignal.com/;
connect-src 'self' onesignal.com;
style-src 'self' onesignal.com;
```
