### ISSUE TITLE
Feature-request: add position: top-right for subscription bell

### ISSUE THREAD

**Issue by MakarovAV** [OneSignal/OneSignal-Website-SDK#326]
**Description:**

There is an option "position" for customizing subscription bell:
https://documentation.onesignal.com/v3.0/docs/customize-permission-messages#section-customize-subscription-bell

There are only two options for placing bell now: 'bottom-left' and 'bottom-right'. 
But my business guys really wants this bell in top right corner of the screen.

Now I am working around it by dirty overriding stylesheets.

**Steps to Reproduce Issue:**

Feature request, not a bug, don't need to reproduce

**Anything else:**

**Comment by nickpunt** [comment]
Hi there,
Unfortunately we don't have plans to support the subscription bell rendered from the top of the page. We're not convinced adding this option to the subscription bell would provide a good user experience for the vast majority of sites out there due to the way most sites are structured, nor is this something we've seen supported in similar products (e.g. Intercom). 

We built the OneSignal Web SDK to be flexible enough for developers to build custom user interfaces for prompting, so we'd recommend going that route instead. 

Best of luck!
