### ISSUE TITLE
Testing in localhost (SdkInitError: OneSignal)

### ISSUE THREAD

**Issue by PsyGik** [OneSignal/OneSignal-Website-SDK#327]
**Description:**

Trying to test angular 4 app in localhost with onesignal integration. Getting the following error 
`SdkInitError: OneSignal: This web push config can only be used on https://mydomain.com. Your current origin is http://localhost:4200.`

This a new app which we configured recently. We had configured two other apps before December 2017, which never gave this error. 

**Anything else:**
This is how the configuration looks like
````
OneSignal.push(['init', {
            appId: Constants.ONE_SIGNAL_APP_ID,
            safari_web_id: Constants.ONE_SIGNAL_APP_ID_SAFARI,
            autoRegister: true,
            allowLocalhostAsSecureOrigin: true,
            notifyButton: {
                enable: false
            }
        }]);
````

How do we test push notification delivery on localhost?

**Comment by jasonpang** [comment]
Hi @PsyGik,

Web push apps created in or after December 2017 have an extra check to make sure the Site URL specified in your OneSignal dashboard is the only site using your web push config. 

When using a web push app across multiple sites, the browser treats each site separately with its own push subscription and storage. Suppose a website made web push available on three separate origins: https://site.com, https://www.site.com, and https://login.site.com each using the same OneSignal app. Previously, one person subscribing to these three separate origins would have three separate subscriptions on the OneSignal app. It isn't possible to map these three separate subscriptions back to the same person, unless the person happened to log in by a unique identifier like an email address and you tagged subscriptions with their email.

We noticed some users hosting sites that were accessible from both https://site.com and https://www.site.com, where OneSignal web push would be set up to work on each origin. Eventually, they would collect "duplicate" subscriptions, from people subscribing to both site origins, that weren't possible to de-duplicate.

This origin check fixes that issue. Since web push in general follows the "each origin has its separate and unique storage and subscription" policy, this restriction fits that model.

For testing locally, please create a separate development app.

**Comment by PsyGik** [comment]
@jasonpang, It'd be good to have this in the official documentation also. Currently the testing locally section in the FAQs does not mention that a separate app is required for local dev testing.

**Comment by jasonpang** [comment]
Hey @PsyGik,

Thanks for pointing that out! I've updated https://documentation.onesignal.com/docs/web-push-setup-faq#section-how-do-i-test-my-site-on-a-local-environment- to mention clients should use a separate app for local testing.

**Comment by TrymBeast** [comment]
Hey @jasonpang!

Couldn't you guys let the client choose this behavior? Defaulting to the validation being active.
So, now I have "old" apps that works anywhere and new apps that only works on the specified url.

And a pain to setup this for all environments where I work.
