### ISSUE TITLE
SDK version 150085 does not work at all

### ISSUE THREAD

**Issue by Darkside73** [OneSignal/OneSignal-Website-SDK#330]
**Description:**
Tested on local domain.
The configuration is following:
```js
var OneSignal = window.OneSignal || [];
OneSignal.push(function() {
    OneSignal.init({
        appId: '0bdb6ab0-c7ac-49ee-aee8-0a2cc6831163',
        autoRegister: false,
        allowLocalhostAsSecureOrigin: true,
        notifyButton: {
            enable: false
        },
    });
});
```
These file are accessible from web root path:
* manifest.json
* OneSignalSDKUpdaterWorker.js
* OneSignalSDKWorker.js

**Steps to Reproduce Issue:**

1. Visit local domain
2. Run ```OneSignal.log.setLevel('trace')```
3. Refresh page

Console logs:

```
OneSignal Web SDK loaded (version 150085, Host environment).
OneSignal: Set pageTitle to be '...'.
[Service Worker Update] Worker did not reply to version query; assuming older version.
```

No notification promt and no service worker registered

**Comment by jasonpang** [comment]
Hi @Darkside73,

If the expected behavior in this issue is the lack of a notification prompt or registration of a service worker, know that when `autoRegister` is set to `false`, the SDK will not prompt for notification permissions automatically. Until the user grants notification permissions, a service worker won't be installed.

To resolve this, you can either set `autoRegister: true` or use one of our prompting APIs to show the notification prompt at any time you choose.

**Comment by Alien10123** [comment]
Just saying, you leaked your onesignal appid!
