### ISSUE TITLE
site.webmanifest instead of manifest.json

### ISSUE THREAD

**Issue by shoulders** [OneSignal/OneSignal-Website-SDK#332]
**Description:**

There was a discussion over at realfavicongenerator.net that the correct manifest file name should be site.webmanifest. https://github.com/RealFaviconGenerator/realfavicongenerator/issues/342

Your file https://github.com/OneSignal/OneSignal-Website-SDK/releases/download/https-integration-files/OneSignal-Web-SDK-HTTPS-Integration-Files.zip uses manifest.json

**Steps to Reproduce Issue:**

no steps to reproduce this.

**Anything else:**

(any other information here)

I have searched the issues for site.webmanifest and manifest.json and found nothing.

Thanks

**Comment by jasonpang** [comment]
Hi @shoulders,

It looks like [`application/manifest+json`](https://www.w3.org/TR/appmanifest/#media-type-registration) is the official media type now. There's a couple reasons I don't think we'll be changing this:

a) The manifest file, originally used in older versions of Chrome, is being increasingly replaced by the W3C VAPID standard for web push subscription. Only older versions of Chrome and older forks of Chrome rely on the manifest file. The majority of subscriptions now take place with VAPID, and the manifest file isn't used at all for VAPID.

b) We haven't gotten any reports of `manifest.json` with a media type `application/json` to not be working. Our existing approach has consistently been working. There's a risk web servers might return an incorrect media type because while it recognizes `.json` should return `application/json`, web servers may not recognize `.webmanifest` and return `application/octet-stream` and require users to add additional server configuration. We definitely don't want users to have to do any extra work to add server configuration.

c) Tying to b), although the official spec has been updated with this new media type, many examples including [Google's official walkthrough guide](https://developers.google.com/web/fundamentals/push-notifications/) and [their sample](https://github.com/GoogleChrome/samples/blob/gh-pages/push-messaging-and-notifications/index.html#L45) use `manifest.json` with a media type of `application/json`. This is also we originally chose that file name and media type. There's no risk browsers not using VAPID won't support `manifest.json` and `application/json` since it's so well known.
