### ISSUE TITLE
SendTag injection

### ISSUE THREAD

**Issue by yoye** [OneSignal/OneSignal-Website-SDK#333]
In documentation, this is recommended to send data like `user_id`, `user_type` or `user_privileges` but this seems really unsecure. In any browser's console you can easily call `OneSignal.sendTag('user_id', otherUserId)` or `OneSignal.sendTag('user_privilege', 'admin')`.

Now if the app use tags to send segmented notification or personnal message another user is connected to this messages, a real man in the middle.

Should not this data be sent signed?

**Comment by jasonpang** [comment]
Hi @yoye,

It sounds like you're talking about a visitor using the browser's developer tools to run malicious JavaScript code. Any code the visitor runs would only affect his page view and his push record. He may unsubscribe from push via the browser's console or send random tag values, but this would only affect his push record. In the case of `OneSignal.sendTag('user_privilege', 'admin')`, this would only set his push record's tag `user_privilege` to `admin` and no one else's. In the case of `OneSignal.sendTag('user_id', otherUserId)`, the probability of guessing another visitor's `otherUserId` on your same app is negligible since they are randomly generated values like `59e570bf-ed47-4f48-8fa6-3dc96c7952a5`.

In general, anything that can be done via the browser's developer tools is outside our SDK's threat model since this is a physically-local attack and can't be defended against as described in [Chrome's Security FAQ](https://dev.chromium.org/Home/chromium-security/security-faq#TOC-What-about-unmasking-of-passwords-with-the-developer-tools-).

**Comment by yoye** [comment]
Hi @jasonpang,

I've understand the scope of this call. What I'm saying is that after attibuting some privilege or type or level. This user could get notification that are restricted and of which he should not have access. 

I think the documentation must give some advice about security because one it explain how to grant user level (which is really easy to bypass) and on another how to create a segment to send data to this level.

https://documentation.onesignal.com/docs/add-user-data-tags
https://documentation.onesignal.com/docs/data-tags
