### ISSUE TITLE
Pre-existing OneSignal users can't re-subscribe to OneSignal if the site is using a new app

### ISSUE THREAD

**Issue by mintplugins** [OneSignal/OneSignal-Website-SDK#335]
**Description:**

Using the custom Javascript SDK, if you switch OneSignal Apps (delete and re-create), a user who previously subscribed cannot resubscribe. 

**Steps to Reproduce Issue:**

1. In Google Chrome on a site with OneSignal configured, allow notifications by running:
```
OneSignal.registerForPushNotifications({
            modalPrompt: true
});
```

2. Then delete your One Signal application and re-create a new one for the same site. 

3. Then, in the same browser you used in Step 1, and after changing your APP IDs to match your new app in the init call, attempt to resubscribe the user. While the prompt will open, the user will not actually be subscribed.

```
OneSignal.push(function() {

          // Show the prompt to register
          OneSignal.registerForPushNotifications({
                 modalPrompt: true
           });

});
```

You can confirm the issue because the user id is `NULL` if you do this:
```
OneSignal.push(function() {   
// If there is no user
    OneSignal.getUserId(function(userId) {
             if ( null == userId ) {
                   console.log( "this user id is blank, and so they cannot subscribe" );
             }
      });
});
```

You should get the console message because the user ID does not exist in OneSignal. Attempting to them register them results in nothing happening. The prompt shows, but the user is not actually subscribed. 

At this point the user is unable to subscribe.

**Comment by jkasten2** [comment]
@mintplugins Thanks for reporting with step by step details. Since the issue is occurring in this specific edge case and would only happen in a pre-production state when test we are going mark this as a lower priority. However let us know if this happens in more common states than switching app ids and we can definitely give this higher priority.

**Comment by RichardSilveira** [comment]
The same issue reported by @mintplugins had happened with me too. 
I'm using oneSigal by first time and I have setted up my application under development (on my machine) with `localhost` url and later setted up another oneSignal APP pointing to my public url.

This issue is annoying (to new users at least) 'cause  we were lost, until debugging the OneSignal SDK and notice the  null userId from `OneSignal.getUserId(function(userId)`. Once I have noticed it, i tried on firefox and everything have worked fine.

I'm becoming a fan of OneSignal solution, but i spent a reasonable time with this issue... (and still don´t figure out how to remains with two apps for my solution  _one for development purposes and another for my "real" application_ )

**Comment by RichardSilveira** [comment]
The problem had happened 'cause a kind of misconception by my own.
Thanks a lot by the e-mail support @fatsjohonimahnn !

**Comment by jkasten2** [comment]
I believe this is currently no longer an issue, we have made a number of changes such as  #521 which should have corrected this problem.

If you are still able to reproduce the issue please provide steps to reproduce if different then the above.

**Comment by shakoorattari** [comment]
we are still getting same issue in safari. any idea?
