### ISSUE TITLE
400 : PUT https://onesignal.com/api/v1/players/null

### ISSUE THREAD

**Issue by zerodiff** [OneSignal/OneSignal-Website-SDK#338]
**Description:**

According to our JS error tracking, since mid day March 23, we've started to get this JS error a lot:

400 : PUT https://onesignal.com/api/v1/players/null

We haven't changed any of our OneSignal calls since January, so we assume this is caused by a change in the OneSignal library, but it might be a change in what/how we're sending pushes. It might just be solved by a `null` check in the OneSignal code, but I'm not sure if it's a deeper issue.

I'd also like to stop spamming you with PUT requests that aren't going to work.

**Steps to Reproduce Issue:**

Unfortunately I don't have the steps or a stack trace, just this showing up in the logs.

**Anything else:**

During the same session, these calls to OneSignal succeeded:

POST https://onesignal.com/api/v1/notifications
POST https://onesignal.com/api/v1/players
PUT https://onesignal.com/api/v1/players/{the player id}

**Comment by jasonpang** [comment]
Hi @zerodiff,

Thanks for reporting this. This issue should be fixed now in the latest version of the SDK. It may take up to 3 days for the error occurrences to subside due to our caching time.

**Comment by etticat** [comment]
We are using the OneSignal Android SDK. We observe a very similar problem since a month ago. Maybe it's related. 

around 70% of calls to "onesignal.com/api/v1/players" result in a 400 error. 

From the attached graph you can see that the success rate gradually decreased over the last month.

![image](https://user-images.githubusercontent.com/4976684/56682824-493f0200-66c4-11e9-861b-0379c8336166.png)

Could this be related?
