### ISSUE TITLE
undefined is not an object (evaluating 'navigator.serviceWorker.getRegistration')

### ISSUE THREAD

**Issue by zerodiff** [OneSignal/OneSignal-Website-SDK#341]
**Description:**

I see a lot of JS errors for Safari sessions (only Safari desktop 11.0 to 11.3):

```
window.safari.pushNotification.permission(this.config.safariWebId), [2, {
subscribed: !("granted" !== o.permission || !o.deviceToken || !n),
optedOut: i
}]): [4, this.context.serviceWorkerManager.getActiveState()];
case 2:
  // this is the line with the error
  return s = r.sent(), [4, navigator.serviceWorker.getRegistration()];
case 3:
  return a = r.sent(), [4, this.context.permissionManager.getNotificationPermission(
    this.context.appConfig.safariWebId)];
case 4:
  return u = r.sent(), c = s === E.ServiceWorkerActiveState.WorkerA || s === E.ServiceWorkerActiveState
    .WorkerB, a ?
```

This is the JavaScript, so presumably that was once TypeScript. I think it's from `SubscriptionManager.ts` here:

```
  private subscribeSafariPromptPermission(): Promise<string | null> {
    return new Promise<string>(resolve => {
      window.safari.pushNotification.requestPermission(
        `${SdkEnvironment.getOneSignalApiUrl().toString()}/safari`,
        this.config.safariWebId,
        {
          app_id: this.config.appId
        },
        response => {
          if ((response as any).deviceToken) {
            resolve((response as any).deviceToken.toLowerCase());
          } else {
            resolve(null);
          }
        }
      );
    });
  }
```

**Steps to Reproduce Issue:**

Again, unfortunately no steps I have, just errors I see reported.

**Anything else:**

This seems to be related to another exception I'm seeing only on Safari:

`undefined is not an object (evaluating 'window.safari.pushNotification')`

I honestly don't know when this would ever not be defined in Safari, but there doesn't look like a check before it's called in `PermissionManager.ts` in `getSafariNotificationPermission`, where this seems to be being thrown (just a check that the browser is Safari). Speculation is that in some configuration of Safari 11, it won't define it.

**Comment by jasonpang** [comment]
Thanks for reporting @zerodiff.

Sounds like the failing line is [SubscriptionManager.ts:701](https://github.com/OneSignal/OneSignal-Website-SDK/blob/master/src/managers/SubscriptionManager.ts#L701):

```js
const workerRegistration = await navigator.serviceWorker.getRegistration();
```

Service workers aren't supported in this version of Safari so that line will fail.

It's not supposed to get there though because of the earlier line in the same method [SubscriptionManager.ts:687](https://github.com/OneSignal/OneSignal-Website-SDK/blob/master/src/managers/SubscriptionManager.ts#L687):

```js
if (SubscriptionManager.isSafari()) {
      ...
      return {
        subscribed: isSubscribedToSafari,
        optedOut: optedOut,
      };
    }
```

`window.safari` is true on top frames in Safari but is undefined on child iframes. This will cause the code to continue to the `navigator.serviceWorker.getRegistration()` statement, which would fail at that point.

Do you know if you happen to be using Safari web push on a non-top frame on your site?

**Comment by zerodiff** [comment]
We may be calling the SDK in an iframe or web view in some circumstances. We're going to stop doing that, and hopefully the we'll see the errors go away.

**Comment by jkasten2** [comment]
@zerodiff Thanks for the details. Let us know if you are still seeing an error and we can reopen this issue.

**Comment by ozgurozkan123** [comment]
I see the same error : undefined is not an object (evaluating 'window.safari.pushNotification.permission')
