### ISSUE TITLE
REST API - Big Image Parameter

### ISSUE THREAD

**Issue by BrianMoreno1994** [OneSignal/OneSignal-Website-SDK#343]
**Description:**

Hi, I'm currently using the [REST API](https://documentation.onesignal.com/reference) to send push notification. I would like to know what is the parameter to send a big image on Chrome for Android and for Windows ([example on Windows](http://i.imgur.com/9mAdbTH.png) and [example on Android](https://i.imgur.com/onBdl7m.png)). 

**Steps to Reproduce Issue:**

I'm currently using the parameter `chrome_web_image` but whenever I send the request I get the following error:
`Error code: Request failed with status code 500`.

I'm using a PHP SDK to consume the API ([https://github.com/namnv609/php-onesignal-sdk](https://github.com/namnv609/php-onesignal-sdk)) and this is my code:

```
use NNV\OneSignal\OneSignal;
use NNV\OneSignal\API\Notification;

$oneSignal = new OneSignal("MY-USER-AUTH-KEY");

//Send notification
$notification = new Notification($oneSignal, "App-ID", "REST API key");

$notificationData = [
    'contents' => [
        'en' => $_POST["message"],
    ],
    'headings' => [
        'en' => $_POST["title"],
    ],
    'included_segments' = ['All'];
    'chrome_web_image' = $_POST["image_url"];
    'big_picture' = $_POST["image_url"];
    'isChromeWeb' => true,
    'isAndroid' => true,
    'isSafari' => true,
];

$send = $notification->create($notificationData);
```

Any help is greatly appreciated. :)

**Comment by gdeglin** [comment]
Unfortunately we're not familiar with this PHP SDK since we don't maintain it ourselves, but I see that in your example code, you have a `;` instead of a `,` after `['All']` and some of the other values. Also you use `=` in several places where you should have `=>`, so this example code probably wouldn't run.

You parameter names look fine, except you should not send "big_picture" or "isAndroid" since these parameters are for native Android applications, not for web push.

Most likely the issue here is that your payload is being generated incorrectly, or that you need to remove `isAndroid`. Please feel free to reply here and we'll re-open the issue if you are able to confirm that the issue is with our server and not your code or the library you are using.
