### ISSUE TITLE
[localhost] Installing service worker undefined/undefined?appId=

### ISSUE THREAD

**Issue by yuyiip** [OneSignal/OneSignal-Website-SDK#347]
**Description:**
Recently, when I run my application in localhost, installing service worker throws an error. When I trace it, it says **Installing service worker undefined/undefined?appId={someid}** It seems the SDK tries to fetch something from **http://localhost:3000/undefined/undefined?appId=**. 

Inspecting the code, it seems the SDK treats localhost as insecure origin. Therefore, the workerPath is undefined.

**Steps to Reproduce Issue:**
It only happens on localhost and Chrome. Safari works fine.

**Comment by jkasten2** [comment]
@yuyiip It is recommend to setup your system to use https://localhost/ since this will match production. However if your having issues switching your localhost to HTTPS you can follow this guide to allow the SDK support HTTP on localhost.
https://documentation.onesignal.com/docs/web-push-options#section-local-testing

**Comment by jkasten2** [comment]
@yuyiip We just fixed an issue in the latest release where `allowLocalhostAsSecureOrigin` was not working for HTTP.
https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/150404
