### ISSUE TITLE
JSON received: {"allresponses":false}

### ISSUE THREAD

**Issue by landry161** [OneSignal/OneSignal-Website-SDK#353]
Good Morning.
I am using the rest api to sent notification. I can send messages from the dashboard, but now when whith the rest API i got the message. 

JSON sent:
{"app_id":"APP_ID","included_segments":["All"],"data":{"foo":"bar"},"contents":{"en":"English Message"}}

JSON received:
{"allresponses":false} 
Can yo help me please?
Thanks.

**Comment by jkasten2** [comment]
@landry161 I don't see anything wrong with the message body you pasted. I recommend checking you are hitting the correct URL of `https://onesignal.com/api/v1/notifications` and have required `Authorization` HTTP header needed to target by `included_segments`. Note that this should only be done from your own server (Not in your javascript in the browser) when adding your `Authorization` header.

The json `{"allresponses":false}` is never returned from OneSignal so this must be something the library your are using is returning.

Since this question is related to the OneSignal REST API instead of this SDK please contact OneSignal support from the messing bubble on the bottom right while signed to the OneSignal dashboard if the above does to work.

**Comment by landry161** [comment]
Ok thanks for the response.
the real problem is that:
I use the rest API. I send message from the OneSignal Dashboard and i receive notifications on the mobile.
With the REST API when i try this url on my localhost the message is sent to the mobile
http://localhost:81/myproject/v2/sendNotification.php
And the response is
JSON sent:
{"app_id":"APP_ID","included_segments":["All"],"data":{"foo":"bar"},"contents":{"en":"English Message"}}

JSON received:
{"allresponses":"{\"id\":\"APP_ID\",\"recipients\":1}"}

But when i use it on my my server the response is false.

**Comment by jkasten2** [comment]
If you are using the exact same code in production as well as you local machine I recommend checking that you are using the same PHP version and the same HTTP library.

**Comment by landry161** [comment]
Ok last time i tried it on other server and works fine.
