### ISSUE TITLE
Failed to register/update Service Worker

### ISSUE THREAD

**Issue by nasr18** [OneSignal/OneSignal-Website-SDK#364]
I'm getting this error in console 
```Failed to register/update a ServiceWorker for scope ‘https://dev.tmmmt.com/’: Bad Content-Type of ‘text/html’ received for script ‘https://dev.tmmmt.com/OneSignalSDKWorker.js?appId=#########’. Must be ‘text/javascript’, ‘application/x-javascript’, or ‘application/javascript’.```

but working fine in localhost.

**Comment by AcidRaZor** [comment]
Whatever CMS you have going, can't find the file, and HTML response takes over instead of serving the file.

"But it's working on my machine". Check if OneSignalSDKWorker.js exists in the root of your website and that, when you access it, you don't see "Login to your Account" page

**Comment by nasr18** [comment]
Actually I wanna use this `OneSignal` web push in my `angular 5` app. Already `angular service worker` is there. This one not displaying in `service-worker` tab.

**Comment by AcidRaZor** [comment]
Well the PC is telling you it's not working. I gave you the reason why it's not working. It is up to you now to modify it so that, instead of showing tmmmt.com's login page (which is HTML and not JavaScript) when trying to access OneSignalSDKWorker.js, to actually serve OneSignalSDKWorker.js to the browser so that you can avoid the error you got above.

**Comment by jkasten2** [comment]
@nasr18 I took a look and it looks like you fixed this on your end. This error can happen if you are returning a 404 page with html instead of hosting the javascript file correctly.
