### ISSUE TITLE
Service Worker ReactJS conflit with OneSignal Service Worker (DOMException: Only the active worker can claim clients.)

### ISSUE THREAD

**Issue by inaldobrandao** [OneSignal/OneSignal-Website-SDK#429]
I initialize OneSignal in the head of my application, but when I give permission to receive notifications, I get this error:

DOMException: Only the active worker can claim clients.

I understood that you are conflicting the Service Worker of my Create React App with the One Signal Service Worker, any idea how to solve this problem?

**Comment by jkasten2** [comment]
@inaldobrandao Only one service worker can be active for a URL. To work around this browser limitation you will need to move your exiting service worker into OneSignal's with an `importScripts`. More details note below.
https://documentation.onesignal.com/docs/web-push-setup-faq#section-can-onesignal-integrate-with-another-service-worker-on-my-site-or-a-progressive-web-app-

**Comment by jlubeck** [comment]
@inaldobrandao where you able to do this without ejecting the Create React App? Care to share your solution?

**Comment by nagman** [comment]
Hi there,

Same problem here. I have my Create React App PWA, and it worked great until now.
Since I'm trying to implement OneSignal along with it, I have strange bugs, like my main ServiceWorker telling again and again that a new version of the website is available, and sometimes no notifications at all from OneSignal.

Is there a way to import the react service worker into the onesignal's one (without ejecting), or to import the onesignal service worker into the react's one?
Or any other mean to make work the two service workers together?

As PWAs are the future, it should have been solved since long.
You can't have a PWA that doesn't handle notifications nowadays.

**Comment by jkasten2** [comment]
@nagman I recommend checking out the following guide on OneSignal's documentation.
https://documentation.onesignal.com/docs/web-push-setup-faq#section-can-onesignal-integrate-with-another-service-worker-on-my-site-or-a-progressive-web-app-

**Comment by nagman** [comment]
@jkasten2 Thanks but I've already read this.

My question is: How can I implement this with React? Especially with Create React App.

In my cra app, I import my service worker in my src files, and then it compiles to the final service worker. So the link you gave doesn't solve my issue, as I can't register to a service worker that has not been compiled yet.

But I've given up with OneSignal and I opted for a self-made push notifications system. So that I can really undestand what's going on with my service workers, with the Push API, the Notification API, and so forth.

For anyone who's struggling with CRA and Push Notifications, here are the two articles that helped me:  
https://medium.com/izettle-engineering/beginners-guide-to-web-push-notifications-using-service-workers-cb3474a17679  
https://medium.com/@seladir/how-to-implement-web-push-notifications-in-your-node-react-app-9bed79b53f34

**Comment by inaldobrandao** [comment]
@jlubeck I used Firebase FCM.
