### ISSUE TITLE
[Service Worker Installation] Installing service worker failed TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

### ISSUE THREAD

**Issue by tanveerrafiqueIVL** [OneSignal/OneSignal-Website-SDK#490]
**Description:**
I am trying to integrate OneSignal with my Angular 5 app. I have placed manifest.json, OneSignalSDKWorker.js and OneSignalSDKUpdaterWorker.js inside src folder and made entry under assets in .angular-cli.json so that these files become accessible, but I am still facing this issue of service worker installation failure.
Error is GET http://localhost:4200/OneSignalSDKWorker.js?appId=xxx-xxx--xxx 404

Any help will be really appreciated. Thanks.

**Comment by fatsjohonimahnn** [comment]
You need to add these files to the root directory so they are accessible.

If you want to test on localhost, please use  http://localhost:3000 or https://localhost:38237 for example in the Site URL on the OneSignal dashboard. Please use our SDK version and don't use our local version for development.

More on setting up localhost here: https://documentation.onesignal.com/docs/web-push-setup-faq#section-how-do-i-test-my-site-on-a-local-environment-

**Comment by tanveerrafiqueIVL** [comment]
Hi @fatsjohonimahnn, the directory in which I am placing those files is src when I try to fetch http://localhost:4200/manifest.json it is accessible but the OneSingalSDKWorker.js. 
My main question is that what am I doing wrong in placing files. Angular really does know about those files as I have referenced them in .angular-cli.json. Do you have any working example with angular2+?

**Comment by Sturgelose** [comment]
@fatsjohonimahnn, I have a setup but using WorkBox instead of the default service worker setup in Angular 5, though I guess all this is quite similar. 

Mostly, the first check you should do is to make sure that when you do `ng build --prod` the files are located properly inside of the `dist/apps/<your-app>`. If that isn't happening, that means something is wrong with the Angular.json.

In my case I just had to add 
```
"projects": {
   "myProject": {
       "architect": {
           "build": {
              "options": {
              "apps/dash/src/OneSignalSDKUpdaterWorker.js",
              "apps/dash/src/OneSignalSDKWorker.js"
....
```

This loads the OneSignal SDK files into the `/dist` folder.
However, note that Angular + OneSignal integration has some issues, as OneSignal Service Worker uses the `skipWaiting` and `claimUsers` without asking, which means that might trigger updates in your website without being able to warn the user (if you are trying to notify the user about updates before updating). Plus it uninstall and installs service workers a couple of times for its update process...

**Comment by fatsjohonimahnn** [comment]
@Sturgelose Unfortunately I am not too familiar with Angular setup, however if you are adding our service workers, they should be in the root directory.

There are generally 3 options available if you can not add the service workers to the root directory.

1 - You can add an HTTP Header to your server to allow access to the service workers
2 - Only Subscribe uses within the subdirectory
3 - Use "My site is not fully HTTPS" option in the site configuration

For more details on these options, please see: https://documentation.onesignal.com/docs/web-push-setup-faq#section-can-onesignal-sdk-files-be-served-from-a-subfolder-of-my-site-

You would set the path, scope and service worker names in the onesignal.com dashboard > Your app > Settings > All browser config > Step 5 Advanced.

**Comment by rgomezp** [comment]
Closing due to no response
