### ISSUE TITLE
TypeError: navigator.permissions is undefined

### ISSUE THREAD

**Issue by emdotem** [OneSignal/OneSignal-Website-SDK#545]
**Description:**
When allowing the notification consent in Firefox, I got an unexpected: 
```
Service worker event waitUntil() was passed a promise that rejected with 'TypeError: navigator.permissions is undefined'. OneSignalSDKWorker.js:1:110695
```

Unfortunately I can't show the url since the platform is private.

**Comment by jkasten2** [comment]
@emdotem Thanks for reporting! I was able to narrow down the issue to [ServiceWorker.ts#L876](https://github.com/OneSignal/OneSignal-Website-SDK/blob/150707/src/service-worker/ServiceWorker.ts#L876) where `navigator.permissions.query` is called from the serviceWorker context.

In Chrome, `navigator.permissions` is available however on Firefox it is `undefined` in the serviceWorker.

This error only happens when the service worker fires the `pushsubscriptionchange` event, which only happens when the push token changes. Since this SDK asks the browser for the token each time the user returns to the site this error shouldn't cause any issues. However it won't be handling background changes of the token so we look into fixing this issue in the future.

**Comment by rgomezp** [comment]
This should be fixed in the next release
