### ISSUE TITLE
If user is opted out, native prompt does not show

### ISSUE THREAD

**Issue by 0shi** [OneSignal/OneSignal-Website-SDK#556]
**Description:**
If the user has opted out / been opted out using `OneSignal.setSubscription(false)`, the native prompt is not shown when `OneSignal.showNativePrompt()` is called. The following is logged when the logging level is set to trace with `OneSignal.log.setLevel('trace')`
> OneSignal: User dismissed the native notification prompt; reprompt after 30 days.

**Steps to Reproduce Issue:**
Performed the following from console after clearing all browser data and stopping the service worker to remove my code from the equation. Used Chrome for easy reset of permissions. Loaded the page once, called `OneSignal.log.setLevel('trace')`, then reloaded the page:
1. Subscribe the user using `await OneSignal.showNativePrompt()` then clicking allow
2. Opt out the user using `OneSignal.setSubscription(false)`
3. Set the user's browser permission back to "Ask" using the webstite controls
4. Call `await OneSignal.showNativePrompt()` and observe that the prompt is not shown

**Anything else:**
I'm testing in a localhost environment with custom code and the following configuration:
- "AUTO RESUBSCRIBE (HTTPS ONLY)" false
- "Treat HTTP localhost as HTTPS for testing" true
- Here is a pastebin of my console logs from page load: https://pastebin.com/gTAnvBA5

**Comment by rgomezp** [comment]
Howdy, 
While this is reproducible, it is a very narrow edge case that will likely never happen since if someone opts out, they will most likely never set the push permission back to "Ask". For this reason, it isn't something we are going to dedicate resources to fixing. If you are having trouble due to this issue, we can surely come up with a workaround. Please don't hesitate to reach out to our support channel at OneSignal.com

Cheers
