### ISSUE TITLE
Safari push open in same window

### ISSUE THREAD

**Issue by tmishutin** [OneSignal/OneSignal-Website-SDK#570]
**Description:**

We are expecting Safari to work the same as Chrome, when clicking on notification. When new notification comes in Safari on Mac and user clicks on it, expected behavior is that SDK will matches a tab with same URL open and load URL in it, in stead of opening new tab every time.

**Steps to Reproduce Issue:**

1. Configure OneSignal with "Matching Strategy": Origin and "Action Strategy": Navigate
2. Open website with domain from push url
3. Push notification to Safari browser
4. Click on notification
5. New tab is opened.

**Anything else:**

(any other information here)

**Comment by rgomezp** [comment]
I'm not familiar with the settings in the first repro step. In either case, this isn't something we would likely fix any time soon

**Comment by jkasten2** [comment]
@tmishutin  Unfortunately this is a limitation of Safari on macOS. Since the browser doesn't use the standard Push API with a ServiceWorker as all other browsers do it isn't possible to control this behavior. The browser will always open a new tab on notification click and Safari does not provide any options to control this with their proprietary API.

**Comment by tmishutin** [comment]
@jkasten2 somehow Whatsapp and some other messengers managed to do it? So it's not a limitation of the browser, but push technologie I guess?

**Comment by jkasten2** [comment]
@tmishutin It is possible Whatsapp is using the Notification API and a websocket instead of Push. A way to tell is if you don't get notifications when Safari is completely close or if you don't have any tabs open to Whatsapp. Let us know if this is case!
