### ISSUE TITLE
Sometimes I receive the following notification "The site has been updated in the background"out of nowhere?

### ISSUE THREAD

**Issue by kanodia** [OneSignal/OneSignal-Website-SDK#60]
Sometimes when  I send a notification, I receive the following notification with the content as "The site has been updated in the background".

I never write this text. I think it is an one signal SDK bug. How can I fix this?

**Comment by jasonpang** [comment]
Hi there,

The message `This site has been updated in the background` is a forced message from the Chrome browser when our SDK cannot fetch the notification contents to retrieve. Notification contents are not sent to our background worker; instead we receive a signal to display a notification and then we fetch the notification contents from our server. This error can happen if the internet connection suddenly becomes flakey when trying to receive notifications (very rare but possible), or if the notification contents have been already retrieved (can happen due to some corrupted state). Could you please provide the public URL to your site so that we can investigate the issue more? You can always email us at support@onesignal.com to privately provide the URL. There may be another bug we've recently discovered that may cause this message.

**Comment by visheshmahale1994** [comment]
Hii, 
      This is our php code for sending push notifications.some we get write data and some times we get wrong data that the site has been updated in the background. 
      The same issue we face while sending notification from one signal Dashboard also.

<?PHP
    if(isset($_GET["data"]))
    {   
        $listofID = $_GET["data"];
    }
    if(isset($_GET["heading"]))
    {   
        $heading = $_GET["heading"];
    }
    if(isset($_GET["message"]))
    {   
        $message = $_GET["message"];
    }
    if(isset($_GET["icon"]))
    {   
        $icon = $_GET["icon"];
    }
    if(isset($_GET["clickurl"]))
    {   
        $clickurl = $_GET["clickurl"];
    }
 if(strcmp($clickurl,'rofr') == 0){
     $clickurl = 'https://xxxxxxxxx.com/';
   }else{
      $tempurl = "https://xxxxxxxxxxxxxxx.com";
      $clickurl =    $tempurl  . $clickurl  ; 
   }

 function sendMessage($listofID,$heading,$message,$clickurl,$icon){
 $heading = array(
      "en" => $heading
      );
    $message = array(
      "en" => $message
      );
    $s = explode(",", $listofID);

    $fields = array(
      'app_id' => "xxxxxxxxxxxxxxxxx",
 //   'included_segments' => array('All'),
      'data' => array("foo" => "bar"),
      'headings' => $heading, 
      'contents' => $message,
      'include_player_ids' => $s,
      'url' => $clickurl, 
      'chrome_web_icon' => $icon,
      'firefox_icon' =>  $icon
    );
    
    $fields = json_encode($fields);
    print("\nJSON sent:\n");
    print($fields);
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, "https://onesignal.com/api/v1/notifications");
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json',
                           'Authorization: Basic xxxxxxxxxxxxxxxx'));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($ch, CURLOPT_HEADER, FALSE);
    curl_setopt($ch, CURLOPT_POST, TRUE);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
    $response = curl_exec($ch);
    curl_close($ch);
    return $response;
  }
  
  $response = sendMessage($listofID,$heading,$message,$clickurl,$icon);
  $return["allresponses"] = $response;
  $return = json_encode( $return);
  print("\n\nJSON received:\n");
  print($return);
  print("\n");
?>

**Comment by taufansatrio** [comment]
Any updates on this issue? I am also experiencing this and hoping for a fix/workaround

**Comment by jasonpang** [comment]
Hey @taufansatrio,

Sorry for the delay in getting back to you. The problem wouldn't be in your push code. It's possible our service worker is being overridden by another service worker that's not able to handle the incoming event which is why Chrome shows a forced message instead. Could you please provide the public URL to your site so that we can investigate the issue more? More importantly, please also let us know if you're using any third-party push providers in addition to ours, or if your site installs a service worker.

**Comment by jasonpang** [comment]
Hey @taufansatrio,

Our service workers `OneSignalSDKWorker.js` and `OneSignalSDKUpdaterWorker.js` aggressively overwrite other service workers that are registered with the topmost (site root) service worker scope; would it be possible to import your other service workers into our service worker alternatively?

So for example, currently the contents contents of both `OneSignalSDKWorker.js` and `OneSignalSDKUpdaterWorker.js` are the following:

```js
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');
```

Could you try to modify both the contents of `OneSignalSDKWorker.js` and `OneSignalSDKUpdaterWorker.js` to import your other service worker files like so?

```js
importScripts('https://site.com/my-other-service-worker.js');
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');
```
We recommend the above approach instead of importing our service worker into another file because our web SDK kicks out other workers that are registered on the root scope and replaces it with our files.

Please note that all of this only applies if you're trying to register service workers to the root scope 'https://site.com/other-worker.js'. If you're trying to register a service worker only under a specific sub-directory 'https://site.com/some-subdirectory/other-worker.js', that service worker should not be kicked out (though I could be wrong we haven't really tested that).

More about service workers [can be read here](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers).

**Comment by jasonpang** [comment]
If anybody else is experiencing the original issue mentioned, I've [updated this comment to better explain it](https://github.com/OneSignal/OneSignal-Website-SDK/issues/60#issuecomment-219575912). Most likely a second SW issue.

**Comment by jasonpang** [comment]
Documenting all the ways:

> This site has been updated in the background.

can occur:

Technically, why it occurs: When our service worker receives a push event, it has to fetch the actual notification from OneSignal's servers, since we have (at this time) not yet implemented the new web push payload protocol. If we successfully fetch a notification, we display it. Otherwise this error occurs if we can't display a backup notification.

- No messages to fetch from OneSignal
  - (Potential issue) If notifications are queued slower than they are sent, clients will not have any messages to retrieve when they get the push signal.
- A third-party service worker is running, which will still receive the push event, but will not know what to do. This is a likely case described in the second comment of this thread.
- An IndexedDB error occurs `(ServiceWorker.js:693 DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.(…))` which prevents our service worker from being able to retrieve the necessary settings so the method fails, no notification is displayed, and they get this message
- Internet connection fails when the notification is being retrieved, or possibly some ultra power saving  modes on some devices will let the GCM signal through, but Chrome won't be able to make normal network requests to our server to retrieve the notification due to the ultra power saving mode

**Comment by aumouth** [comment]
I have this issue ("This site has been upgraded in the backgrou..") too.

I have a service worker for a Web App Install Banner, as specified at https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/

The Web App Install Banner calls for the following JS code output by my website to the browser ...
`<script>
// https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function() {
    navigator.serviceWorker.register('/service-worker.js', {scope: '/'}).then(function(registration) {
      // Registration was successful
      console.log('ServiceWorker registration successful with scope: ', registration.scope);
    }).catch(function(err) {
      // registration failed :(
      console.log('ServiceWorker registration failed: ', err);
    });
  });
}
</script>`

How would I modify the above for usage with OneSignal, considering the comment above about OneSignal aggressively overwriting others, and editing the OneSignal[...].js to import.

**Comment by ayumihamsaki** [comment]
@jasonpang I tried your advice coz I have a service worker and it has not fixed my problem updating both the files:

Could you try to modify both the contents of OneSignalSDKWorker.js and OneSignalSDKUpdaterWorker.js to import your other service worker files like so?

```
importScripts('https://site.com/my-other-service-worker.js');
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');
```

I still get the error message: 

`tslib.es6.js:62 Uncaught (in promise) PermissionMessageDismissedError {message: "The permission message was previously dismissed.", name: "PermissionMessageDismissedError", stack: "PermissionMessageDismissedError: The permission me…m/sdks/OneSignalSDK.js:1:1486)↵    at <anonymous>"}`

p.s. Using Google Canary V61

**Comment by miguelmobilat** [comment]
I have the same problem in flutter web, it seems that there is a conflict between the service workers with flutter and onesignal.

```
<!DOCTYPE html>
<html lang="es">


<head>
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta content="A new Flutter project." name="description">

  <!-- iOS meta tags & icons -->
  <meta content="yes" name="apple-mobile-web-app-capable">
  <meta content="black" name="apple-mobile-web-app-status-bar-style">
  <meta content="back_office" name="apple-mobile-web-app-title">
  <link href="icons/Icon-192.png" rel="apple-touch-icon">

  <!-- Favicon -->
  <link href="favicon.png" rel="icon" type="image/png" />

  <title>back_office</title>
  <link href="manifest.json" rel="manifest">
  <script
    src="https://maps.googleapis.com/maps/api/js?key=KEY&loading=async&callback"></script>
  <script src="https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js" defer></script>
  <script defer src="flutter.js"></script>

  <style>
    body {
      margin: 0;
      padding: 0;
      background-color: #101820;
    }

    .container {
      width: 100vw;
      height: 100vh;
      display: flex;
      /* Default Axis is X*/
      justify-content: center;
      /* Main Axis */
      align-items: center;
      /* Cross Axis */
    }

    .indicator {
      width: auto;
    }
  </style>
</head>

<body>
  <div id="loading" class="container">
    <img class="indicator" src="./assets/loading.svg" />
  </div>
  <script>
    const serviceWorkerVersion = null;
  </script>
  <script>
    window.addEventListener('load', function (ev) {
      var loading = document.querySelector('#loading');
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: async function (engineInitializer) {
          let appRunner = await engineInitializer.initializeEngine();
          loading.style.display = 'none'
          await appRunner.runApp();
        }
      });
    });
  </script>
  <script>
    window.OneSignalDeferred = window.OneSignalDeferred || [];
    OneSignalDeferred.push(function (OneSignal) {
      OneSignal.init({
        appId: "KEY",
      });
    });
  </script>
</body>

</html>
```

**Comment by dongph9x** [comment]
@vedmant  @miguelmobilat 
It seems like onesignal's sw is conflicting with some sw, I solved it
Solution: change the path and scope of OneSignalSDKWorker.js so that it is unique
link docs: https://documentation.onesignal.com/docs/onesignal-service-worker-faq#integrating-multiple-service-workers
please search to text: It is ok to put multiple service workers in the same location path, but MUST have unique scope path.

Config Ex:
serviceWorkerParam: { scope: "/onesignal/push-notifications/" },
serviceWorkerPath: "onesignal/push-notifications/OneSignalSDKWorker.js",
