### ISSUE TITLE
Push Notifications not working on Chrome, the notifications are blocked by default

### ISSUE THREAD

**Issue by tiagovale-vakt** [OneSignal/OneSignal-Website-SDK#617]
I am working with OneSignal in order to make my website able to do the subscribe/unsubscribe notifications. However i am having problems with Chrome, cause there is a setting about notification with this message "Blocked to protect your privacy". I did the same test with Firefox and it is woking as expected.

To reproduce this error, you just need to have the OneSignal configured and running on your local machine with "HTTP", then check the site settings for notification.

**Comment by weslei-dias** [comment]
I'm having the same issue after update my chrome version. I read an article about the updates that  Google will do about push notifications.
Is this the reason for onesignal stop to work on chrome?

**Comment by rgomezp** [comment]
It's quite possible it is either 1) user specific or 2) app specific. If you tend to block notifications often, it will default to block as Chrome sees fit. If a specific site/app has a low opt-in rate, Chrome may elect to block automatically due to these rates.

You can find out more on our blog post here: https://onesignal.com/blog/changes-to-chrome-and-firefox-permission-prompting/

**Comment by lamnv5490** [comment]
Hi @tiagovale-vakt , I have experience with this case. Due to new Chrome Cookie Policy, all HTTP site with disrupt with Same Site Cookie warning and in that case, our Signal won't work properly. Either switching to HTTPS or ignoring it and proceed testing on other browsers.

**Comment by rgomezp** [comment]
Howdy @lamnv5490 ,
Thanks for the response! I will go ahead and close this issue
