### ISSUE TITLE
How to use a custom OneSignal Web-SDK build in my project?

### ISSUE THREAD

**Issue by novaknole** [OneSignal/OneSignal-Website-SDK#623]
**Description:**

Hi @rgomezp , I hope you can give me some insights. This is really urgent and necessary. 

OneSignal has its own service worker file which seems to have the following line 
`e.waitUntil(self.skipWaiting())` in its install listener. I also use my own service worker file in which I have `skipWaiting` but only when client throws an event and not in `install` or `activate` event.

The issue here now is that To use onesignal, i have to merge your and my service workers and final service worker would end up having `skipWaiting` in install event. Now, this is a really bad situation for me and I am thinking about removing `skipWaiting` from your install event and host that service worker file of yours myself.

What might be the issue if I remove that line? I've spend so much time with service workers and i don't think it should cause any problem. All it does is if there's a change in service worker file, it takes that to the activated state directly.  And i am happy not to do that.

Can you think of any issues by removing that line?

**Comment by rgomezp** [comment]
Howdy @novaknole ,
I honestly can't say whether or not it is safe to remove since there may be code dependant on it. However, feel free to test this if you have some time and update us with what you find.

Same goes to you @Sturgelose ( #407 )

Take a look at the [Express Webpack](https://github.com/OneSignal/OneSignal-Website-SDK/tree/master/express_webpack) readme for build instructions and local testing.

**Comment by novaknole** [comment]
Question 1) Right now, I just copied/pasted the built version of OneSignalSDKVersion and removed skipwaiting from there, but this is gonna be painful in the future. So if I follow `Express Webpack` example, do i have to do this: Clone the project, remove `skipWaiting`, build it then, and then just copy/paste `OneSignalSDKWorker` to my project? 


Question 2)

I will update what effect `skipWaiting` causes later this sunday or Monday!

**Comment by rgomezp** [comment]
Howdy @novaknole ,
Perhaps it would be easier to add your second service worker to the OneSignal **Express Webpack** sandbox environment since it is already configured to work smoothly with fresh local SDK builds.

**Comment by novaknole** [comment]
howdy @rgomezp 

I can't since my service worker contains `ES6 import statements` so webpack takes care of importing the code later. 

Anyway,  what if I type `yarn build:prod` on master branch of this project and then copy `build/bundles/OneSignalSDKWorker.js` to my project and import it in my service worker? any chance you can think of any downsides?

can we proceed on https://github.com/OneSignal/OneSignal-Website-SDK/issues/625 ?

**Comment by rgomezp** [comment]
Howdy @novaknole ,
The problem is that you would have to change the production origins so that the SDK doesn't look for SDK files at onesignal.com but rather your own public directory on your server.

Here's an example of changing the origins for use with staging: 
```
BUILD_ORIGIN=staging.onesignal.com API=staging API_ORIGIN=staging.onesignal.com yarn build:staging
```

Or you can simply write your custom script in the project's [package.json](https://github.com/OneSignal/OneSignal-Website-SDK/blob/master/package.json#L29). You may need to modify the [publish script](https://github.com/OneSignal/OneSignal-Website-SDK/blob/master/build/scripts/publish.sh) too.

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by nemoneph** [comment]
Hello @novaknole 
I have exactly the same problem. 
skipWaiting() in install is causing problem (I want to control the update of my PWA with a refresh button and trigger skipWaiting manually).

Since this time, do you have found a solution (withou rebuild the SDK..) ?

**Comment by novaknole** [comment]
Hey Clement,

I tried it, made it work but then very strange things started to happen
which were out of sense. So I would not advise to change it. What I ended
up with is I wrote custom push notifications by myself.

**Comment by nemoneph** [comment]
@novaknole Thanks for your quick reply. 
I will try to open an issue and explain why it's can be dangerous to call skipWaiting() on install
