### ISSUE TITLE
dashboard giving wrong Delivery Status

### ISSUE THREAD

**Issue by visheshmahale1994** [OneSignal/OneSignal-Website-SDK#66]
I am sending push Notifications to n devices,after sending message in delivery Status it is showing that the notification sent successfully to all the n devices but  none of the device received any notification.
How can i solve this issue

**Comment by jasonpang** [comment]
Hi,

Could you privately email us with your OneSignal account login email so that we can further investigate the issue?

Could you also provide more details about the issue? Have you ever been able to receive a notification on a device? If so, is this issue happening only some of the time? We can try a few debugging steps later on, thanks!

**Comment by jasonpang** [comment]
Hey @visheshmahale1994,

Let us know if you're still having issues. We'd prefer it if you contact us via support@onesignal.com since we'd like to keep the Web SDK issues strictly related to the web SDK (and this issue is more about our dashboard).
