### ISSUE TITLE
notificationPermissionChange is not fired when a user clicks X button

### ISSUE THREAD

**Issue by justinlee0516** [OneSignal/OneSignal-Website-SDK#707]
**Description:**

notificationPermissionChange is not fired when a user clicks X button in the browser prompt on Chrome.
'granted' and 'denied' events are fired, but 'default' is not fired.

**Comment by rgomezp** [comment]
Howdy,
This event doesn't fire because nothing changed. The main purpose of this listener is to listen to _changes_ in the permission. However, on the Chrome browser after several repeated closings of the native prompt the permission _should_ change and thus will be reflected in the event listener.

Cheers
