### ISSUE TITLE
Fix requireInteraction/persistNotification macOS

### ISSUE THREAD

**Issue by luisjoserivera** [OneSignal/OneSignal-Website-SDK#711]
**Description:**

After #568 requireInteraction/persistNotification is forced to **false** for any Chrome version running on macOS 10.15 or above.

I'm running **Chrome** Version 86.0.4240.80 (Official Build) (x86_64) in **macOS** 10.15.7 (Catalina) and `requireInteraction` works without a problem. YouTube notifications are a clear example, always `requireInteraction=true`.

Maybe there was a specific scenario where a version of Chrome and/or macOS had issues not displaying notifications pushed with `requireInteraction=true` but it was wrong to merge a fix that disables the feature for any further versions.

**Comment by jkasten2** [comment]
@luisjoserivera Thanks for the digging in, confirming, and provides these details!

## My Investigation
I just tested this as well with the following and `requireInteraction` is working.
* Chrome Version 88.0.4324.146 (Official Build) (x86_64)
* MacOS 10.15.6 (Catalina) (19G73)
* Notification generated from https://tests.peter.sh/notification-generator/#requireInteraction=true

Chrome's implementation is interesting here, it seems they worked around the macOS 10.15 notification change by registering Chrome twice in the macOS notification settings.
![image (1)](https://user-images.githubusercontent.com/645861/108586984-31f3ee80-7306-11eb-9af0-bfef923aaccc.png)

I noticed one Chrome entry has "Banner" set and the other "Alerts". Seems to me Chrome uses one or the other based on the `requireInteraction` flag to get this behavior.

Also see the video in Comment 11 in this Chrome ticket as well where they noticed this behavior as well.
https://bugs.chromium.org/p/chromium/issues/detail?id=1064641#c11

## TODO Investigation
* Will attempt this exact same test with will macOS 11 (Big Sur) just to confirm things are still working.
* Since we are here looking at `requireInteraction` might as well investigate if Opera still as the same issue with `requireInteraction`.

## OneSignal SDK Changes
I think it makes sense to revert the macOS 10.15 Chrome workaround fix introduced in PR #568. After we confirm the macOS 11 (Big Sur) behavior too.

**Comment by luisjoserivera** [comment]
Good to know. Sadly I don't have Big Sur to test this.

**Comment by jkasten2** [comment]
@luisjoserivera This is addressed in version 151302 which is now live on cdn.onesignal.com.
https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/151302
