### ISSUE TITLE
[Firefox] Clear cacha & data set removes current subscription (http)

### ISSUE THREAD

**Issue by rjcpereira** [OneSignal/OneSignal-Website-SDK#722]
**Description:**
Im using: My site is not fully HTTPS.
If the user clears the cache and data on firefox, the subscription gets lost. When it subscribes again, it requires the browser permission, even if its set to "granted". After the user click on "Allow" it is created another player on OneSignal Dashboard.

**Steps to Reproduce Issue:**
[https://youtu.be/ou2OUkup_qw](https://youtu.be/ou2OUkup_qw)

**Comment by rgomezp** [comment]
Howdy Ricardo,
I'm unsure what the issue is here. The video you linked is the expected behavior.

You see, when an HTTP site "subscribes" to your website, they are really subscribing to push via the os.tc domain which is HTTPS. This is because HTTPS is required so this is simply a workaround. So if you clear your site data on an HTTP site, you are essentially unlinking the subscription from os.tc.

**Comment by rgomezp** [comment]
Closing due to no response
