### ISSUE TITLE
Language parameter

### ISSUE THREAD

**Issue by PeterPan73** [OneSignal/OneSignal-Website-SDK#848]
**Description:**

Hi, the site is in several languages and the user can change the language himself.

I'm using the NodeJS example with REST API.
Send to a specific segment or all subscribers in NodeJS
`contents: {"en": "English Message", "ru": "Здр"},`

The problem is that I can't pass the language that the user has chosen.
Is it possible to do this in
https://cdn.onesignal.com/sdks/OneSignalSDK.js with some GET parameter
OR in 
`OneSignal.push(function(){ });`
I'm really at a dead end, I'll be happy if you can help me.
Thanks.

**Comment by rgomezp** [comment]
Howdy,
Thank you for your patience.

OneSignal will automatically detect the language preference of the user via the device settings. I suspect your problem is that there is a mismatch between the device settings and the site settings.

The best way to do this would be to tag the users using data tags for their language preference and then create segments to target each one.

You can read more about it [here](https://documentation.onesignal.com/docs/language-localization).
